package mx.com.telcel.sipab.client.coldview;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-10-24T12:32:48.340-06:00
 * Generated source version: 4.0.3
 *
 */
@WebService(targetNamespace = "http://coldview.org/", name = "ColdviewWS")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ColdviewWS {

    @WebMethod(operationName = "Information")
    @Action(input = "http://coldview.org/ColdviewWS/InformationRequest", output = "http://coldview.org/ColdviewWS/InformationResponse")
    @WebResult(name = "InformationResponse", targetNamespace = "http://coldview.org/", partName = "parameters")
    public InformationResponse information(

        @WebParam(partName = "parameters", name = "Information", targetNamespace = "http://coldview.org/")
        Information parameters
    );

    @WebMethod(operationName = "CancelDocumentsCFDI")
    @Action(input = "http://coldview.org/ColdviewWS/CancelDocumentsCFDIRequest", output = "http://coldview.org/ColdviewWS/CancelDocumentsCFDIResponse")
    @WebResult(name = "CancelDocumentsCFDIResponse", targetNamespace = "http://coldview.org/", partName = "parameters")
    public CancelDocumentsCFDIResponse cancelDocumentsCFDI(

        @WebParam(partName = "parameters", name = "CancelDocumentsCFDI", targetNamespace = "http://coldview.org/")
        CancelDocumentsCFDI parameters
    );

    @WebMethod(operationName = "RetrieveDocumentByIndexCFDI_NCR")
    @Action(input = "http://coldview.org/ColdviewWS/RetrieveDocumentByIndexCFDI_NCRRequest", output = "http://coldview.org/ColdviewWS/RetrieveDocumentByIndexCFDI_NCRResponse")
    @WebResult(name = "RetrieveDocumentByIndexCFDI_NCRResponse", targetNamespace = "http://coldview.org/", partName = "parameters")
    public RetrieveDocumentByIndexCFDINCRResponse retrieveDocumentByIndexCFDINCR(

        @WebParam(partName = "parameters", name = "RetrieveDocumentByIndexCFDI_NCR", targetNamespace = "http://coldview.org/")
        RetrieveDocumentByIndexCFDINCR parameters
    );

    @WebMethod(operationName = "RetrieveDocumentListByIndex")
    @Action(input = "http://coldview.org/ColdviewWS/RetrieveDocumentListByIndexRequest", output = "http://coldview.org/ColdviewWS/RetrieveDocumentListByIndexResponse")
    @WebResult(name = "RetrieveDocumentListByIndexResponse", targetNamespace = "http://coldview.org/", partName = "parameters")
    public RetrieveDocumentListByIndexResponse retrieveDocumentListByIndex(

        @WebParam(partName = "parameters", name = "RetrieveDocumentListByIndex", targetNamespace = "http://coldview.org/")
        RetrieveDocumentListByIndex parameters
    );

    @WebMethod(operationName = "RetrieveDocumentByIndexCFDI")
    @Action(input = "http://coldview.org/ColdviewWS/RetrieveDocumentByIndexCFDIRequest", output = "http://coldview.org/ColdviewWS/RetrieveDocumentByIndexCFDIResponse")
    @WebResult(name = "RetrieveDocumentByIndexCFDIResponse", targetNamespace = "http://coldview.org/", partName = "parameters")
    public RetrieveDocumentByIndexCFDIResponse retrieveDocumentByIndexCFDI(

        @WebParam(partName = "parameters", name = "RetrieveDocumentByIndexCFDI", targetNamespace = "http://coldview.org/")
        RetrieveDocumentByIndexCFDI parameters
    );

    @WebMethod(operationName = "RetrieveDocumentListByIndexCFDI_CP")
    @Action(input = "http://coldview.org/ColdviewWS/RetrieveDocumentListByIndexCFDI_CPRequest", output = "http://coldview.org/ColdviewWS/RetrieveDocumentListByIndexCFDI_CPResponse")
    @WebResult(name = "RetrieveDocumentListByIndexCFDI_CPResponse", targetNamespace = "http://coldview.org/", partName = "parameters")
    public RetrieveDocumentListByIndexCFDICPResponse retrieveDocumentListByIndexCFDICP(

        @WebParam(partName = "parameters", name = "RetrieveDocumentListByIndexCFDI_CP", targetNamespace = "http://coldview.org/")
        RetrieveDocumentListByIndexCFDICP parameters
    );

    @WebMethod(operationName = "RetrieveDocumentByIndexCFDI_CP")
    @Action(input = "http://coldview.org/ColdviewWS/RetrieveDocumentByIndexCFDI_CPRequest", output = "http://coldview.org/ColdviewWS/RetrieveDocumentByIndexCFDI_CPResponse")
    @WebResult(name = "RetrieveDocumentByIndexCFDI_CPResponse", targetNamespace = "http://coldview.org/", partName = "parameters")
    public RetrieveDocumentByIndexCFDICPResponse retrieveDocumentByIndexCFDICP(

        @WebParam(partName = "parameters", name = "RetrieveDocumentByIndexCFDI_CP", targetNamespace = "http://coldview.org/")
        RetrieveDocumentByIndexCFDICP parameters
    );

    @WebMethod(operationName = "Version")
    @Action(input = "http://coldview.org/ColdviewWS/VersionRequest", output = "http://coldview.org/ColdviewWS/VersionResponse")
    @WebResult(name = "VersionResponse", targetNamespace = "http://coldview.org/", partName = "parameters")
    public VersionResponse version(

        @WebParam(partName = "parameters", name = "Version", targetNamespace = "http://coldview.org/")
        java.lang.Object parameters
    );

    @WebMethod(operationName = "RetrieveDocumentListByIndexCFDI")
    @Action(input = "http://coldview.org/ColdviewWS/RetrieveDocumentListByIndexCFDIRequest", output = "http://coldview.org/ColdviewWS/RetrieveDocumentListByIndexCFDIResponse")
    @WebResult(name = "RetrieveDocumentListByIndexCFDIResponse", targetNamespace = "http://coldview.org/", partName = "parameters")
    public RetrieveDocumentListByIndexCFDIResponse retrieveDocumentListByIndexCFDI(

        @WebParam(partName = "parameters", name = "RetrieveDocumentListByIndexCFDI", targetNamespace = "http://coldview.org/")
        RetrieveDocumentListByIndexCFDI parameters
    );

    @WebMethod(operationName = "RetrieveDocumentListByIndexCFDI_NCR")
    @Action(input = "http://coldview.org/ColdviewWS/RetrieveDocumentListByIndexCFDI_NCRRequest", output = "http://coldview.org/ColdviewWS/RetrieveDocumentListByIndexCFDI_NCRResponse")
    @WebResult(name = "RetrieveDocumentListByIndexCFDI_NCRResponse", targetNamespace = "http://coldview.org/", partName = "parameters")
    public RetrieveDocumentListByIndexCFDINCRResponse retrieveDocumentListByIndexCFDINCR(

        @WebParam(partName = "parameters", name = "RetrieveDocumentListByIndexCFDI_NCR", targetNamespace = "http://coldview.org/")
        RetrieveDocumentListByIndexCFDINCR parameters
    );

    @WebMethod(operationName = "CancelDocumentCFDI")
    @Action(input = "http://coldview.org/ColdviewWS/CancelDocumentCFDIRequest", output = "http://coldview.org/ColdviewWS/CancelDocumentCFDIResponse")
    @WebResult(name = "CancelDocumentCFDIResponse", targetNamespace = "http://coldview.org/", partName = "parameters")
    public CancelDocumentCFDIResponse cancelDocumentCFDI(

        @WebParam(partName = "parameters", name = "CancelDocumentCFDI", targetNamespace = "http://coldview.org/")
        CancelDocumentCFDI parameters
    );

    @WebMethod(operationName = "RetrieveDocumentByIndex")
    @Action(input = "http://coldview.org/ColdviewWS/RetrieveDocumentByIndexRequest", output = "http://coldview.org/ColdviewWS/RetrieveDocumentByIndexResponse")
    @WebResult(name = "RetrieveDocumentByIndexResponse", targetNamespace = "http://coldview.org/", partName = "parameters")
    public RetrieveDocumentByIndexResponse retrieveDocumentByIndex(

        @WebParam(partName = "parameters", name = "RetrieveDocumentByIndex", targetNamespace = "http://coldview.org/")
        RetrieveDocumentByIndex parameters
    );

    @WebMethod(operationName = "CancelDocument")
    @Action(input = "http://coldview.org/ColdviewWS/CancelDocumentRequest", output = "http://coldview.org/ColdviewWS/CancelDocumentResponse")
    @WebResult(name = "CancelDocumentResponse", targetNamespace = "http://coldview.org/", partName = "parameters")
    public CancelDocumentResponse cancelDocument(

        @WebParam(partName = "parameters", name = "CancelDocument", targetNamespace = "http://coldview.org/")
        CancelDocument parameters
    );
}
