package mx.com.telcel.sipab.client.coldview;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-10-24T12:32:48.368-06:00
 * Generated source version: 4.0.3
 *
 */
@WebServiceClient(name = "COLDviewWS",
                  wsdlLocation = "http://intranet.telcel.com:8050/WARColdviewWS/WARColdviewWS?wsdl",
                  targetNamespace = "http://coldview.org/")
public class COLDviewWS_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://coldview.org/", "COLDviewWS");
    public final static QName COLDviewWSSoap = new QName("http://coldview.org/", "COLDviewWSSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://intranet.telcel.com:8050/WARColdviewWS/WARColdviewWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(COLDviewWS_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://intranet.telcel.com:8050/WARColdviewWS/WARColdviewWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public COLDviewWS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public COLDviewWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public COLDviewWS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public COLDviewWS_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public COLDviewWS_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public COLDviewWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ColdviewWS
     */
    @WebEndpoint(name = "COLDviewWSSoap")
    public ColdviewWS getCOLDviewWSSoap() {
        return super.getPort(COLDviewWSSoap, ColdviewWS.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ColdviewWS
     */
    @WebEndpoint(name = "COLDviewWSSoap")
    public ColdviewWS getCOLDviewWSSoap(WebServiceFeature... features) {
        return super.getPort(COLDviewWSSoap, ColdviewWS.class, features);
    }

}
