
package mx.com.telcel.sipab.client.coldview;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-10-24T12:32:48.118-06:00
 * Generated source version: 4.0.3
 *
 */
public final class ColdviewWS_COLDviewWSSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://coldview.org/", "COLDviewWS");

    private ColdviewWS_COLDviewWSSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = COLDviewWS_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        COLDviewWS_Service ss = new COLDviewWS_Service(wsdlURL, SERVICE_NAME);
        ColdviewWS port = ss.getCOLDviewWSSoap();

        {
        System.out.println("Invoking information...");
        mx.com.telcel.sipab.client.coldview.Information _information_parameters = new mx.com.telcel.sipab.client.coldview.Information();
        mx.com.telcel.sipab.client.coldview.InformationResponse _information__return = port.information(_information_parameters);
        System.out.println("information.result=" + _information__return);


        }
        {
        System.out.println("Invoking cancelDocumentsCFDI...");
        mx.com.telcel.sipab.client.coldview.CancelDocumentsCFDI _cancelDocumentsCFDI_parameters = new mx.com.telcel.sipab.client.coldview.CancelDocumentsCFDI();
        mx.com.telcel.sipab.client.coldview.CancelDocumentsCFDIResponse _cancelDocumentsCFDI__return = port.cancelDocumentsCFDI(_cancelDocumentsCFDI_parameters);
        System.out.println("cancelDocumentsCFDI.result=" + _cancelDocumentsCFDI__return);


        }
        {
        System.out.println("Invoking retrieveDocumentByIndexCFDINCR...");
        mx.com.telcel.sipab.client.coldview.RetrieveDocumentByIndexCFDINCR _retrieveDocumentByIndexCFDINCR_parameters = new mx.com.telcel.sipab.client.coldview.RetrieveDocumentByIndexCFDINCR();
        mx.com.telcel.sipab.client.coldview.RetrieveDocumentByIndexCFDINCRResponse _retrieveDocumentByIndexCFDINCR__return = port.retrieveDocumentByIndexCFDINCR(_retrieveDocumentByIndexCFDINCR_parameters);
        System.out.println("retrieveDocumentByIndexCFDINCR.result=" + _retrieveDocumentByIndexCFDINCR__return);


        }
        {
        System.out.println("Invoking retrieveDocumentListByIndex...");
        mx.com.telcel.sipab.client.coldview.RetrieveDocumentListByIndex _retrieveDocumentListByIndex_parameters = new mx.com.telcel.sipab.client.coldview.RetrieveDocumentListByIndex();
        mx.com.telcel.sipab.client.coldview.RetrieveDocumentListByIndexResponse _retrieveDocumentListByIndex__return = port.retrieveDocumentListByIndex(_retrieveDocumentListByIndex_parameters);
        System.out.println("retrieveDocumentListByIndex.result=" + _retrieveDocumentListByIndex__return);


        }
        {
        System.out.println("Invoking retrieveDocumentByIndexCFDI...");
        mx.com.telcel.sipab.client.coldview.RetrieveDocumentByIndexCFDI _retrieveDocumentByIndexCFDI_parameters = new mx.com.telcel.sipab.client.coldview.RetrieveDocumentByIndexCFDI();
        mx.com.telcel.sipab.client.coldview.RetrieveDocumentByIndexCFDIResponse _retrieveDocumentByIndexCFDI__return = port.retrieveDocumentByIndexCFDI(_retrieveDocumentByIndexCFDI_parameters);
        System.out.println("retrieveDocumentByIndexCFDI.result=" + _retrieveDocumentByIndexCFDI__return);


        }
        {
        System.out.println("Invoking retrieveDocumentListByIndexCFDICP...");
        mx.com.telcel.sipab.client.coldview.RetrieveDocumentListByIndexCFDICP _retrieveDocumentListByIndexCFDICP_parameters = new mx.com.telcel.sipab.client.coldview.RetrieveDocumentListByIndexCFDICP();
        mx.com.telcel.sipab.client.coldview.RetrieveDocumentListByIndexCFDICPResponse _retrieveDocumentListByIndexCFDICP__return = port.retrieveDocumentListByIndexCFDICP(_retrieveDocumentListByIndexCFDICP_parameters);
        System.out.println("retrieveDocumentListByIndexCFDICP.result=" + _retrieveDocumentListByIndexCFDICP__return);


        }
        {
        System.out.println("Invoking retrieveDocumentByIndexCFDICP...");
        mx.com.telcel.sipab.client.coldview.RetrieveDocumentByIndexCFDICP _retrieveDocumentByIndexCFDICP_parameters = new mx.com.telcel.sipab.client.coldview.RetrieveDocumentByIndexCFDICP();
        mx.com.telcel.sipab.client.coldview.RetrieveDocumentByIndexCFDICPResponse _retrieveDocumentByIndexCFDICP__return = port.retrieveDocumentByIndexCFDICP(_retrieveDocumentByIndexCFDICP_parameters);
        System.out.println("retrieveDocumentByIndexCFDICP.result=" + _retrieveDocumentByIndexCFDICP__return);


        }
        {
        System.out.println("Invoking version...");
        java.lang.Object _version_parameters = new java.lang.Object();
        mx.com.telcel.sipab.client.coldview.VersionResponse _version__return = port.version(_version_parameters);
        System.out.println("version.result=" + _version__return);


        }
        {
        System.out.println("Invoking retrieveDocumentListByIndexCFDI...");
        mx.com.telcel.sipab.client.coldview.RetrieveDocumentListByIndexCFDI _retrieveDocumentListByIndexCFDI_parameters = new mx.com.telcel.sipab.client.coldview.RetrieveDocumentListByIndexCFDI();
        mx.com.telcel.sipab.client.coldview.RetrieveDocumentListByIndexCFDIResponse _retrieveDocumentListByIndexCFDI__return = port.retrieveDocumentListByIndexCFDI(_retrieveDocumentListByIndexCFDI_parameters);
        System.out.println("retrieveDocumentListByIndexCFDI.result=" + _retrieveDocumentListByIndexCFDI__return);


        }
        {
        System.out.println("Invoking retrieveDocumentListByIndexCFDINCR...");
        mx.com.telcel.sipab.client.coldview.RetrieveDocumentListByIndexCFDINCR _retrieveDocumentListByIndexCFDINCR_parameters = new mx.com.telcel.sipab.client.coldview.RetrieveDocumentListByIndexCFDINCR();
        mx.com.telcel.sipab.client.coldview.RetrieveDocumentListByIndexCFDINCRResponse _retrieveDocumentListByIndexCFDINCR__return = port.retrieveDocumentListByIndexCFDINCR(_retrieveDocumentListByIndexCFDINCR_parameters);
        System.out.println("retrieveDocumentListByIndexCFDINCR.result=" + _retrieveDocumentListByIndexCFDINCR__return);


        }
        {
        System.out.println("Invoking cancelDocumentCFDI...");
        mx.com.telcel.sipab.client.coldview.CancelDocumentCFDI _cancelDocumentCFDI_parameters = new mx.com.telcel.sipab.client.coldview.CancelDocumentCFDI();
        mx.com.telcel.sipab.client.coldview.CancelDocumentCFDIResponse _cancelDocumentCFDI__return = port.cancelDocumentCFDI(_cancelDocumentCFDI_parameters);
        System.out.println("cancelDocumentCFDI.result=" + _cancelDocumentCFDI__return);


        }
        {
        System.out.println("Invoking retrieveDocumentByIndex...");
        mx.com.telcel.sipab.client.coldview.RetrieveDocumentByIndex _retrieveDocumentByIndex_parameters = new mx.com.telcel.sipab.client.coldview.RetrieveDocumentByIndex();
        mx.com.telcel.sipab.client.coldview.RetrieveDocumentByIndexResponse _retrieveDocumentByIndex__return = port.retrieveDocumentByIndex(_retrieveDocumentByIndex_parameters);
        System.out.println("retrieveDocumentByIndex.result=" + _retrieveDocumentByIndex__return);


        }
        {
        System.out.println("Invoking cancelDocument...");
        mx.com.telcel.sipab.client.coldview.CancelDocument _cancelDocument_parameters = new mx.com.telcel.sipab.client.coldview.CancelDocument();
        mx.com.telcel.sipab.client.coldview.CancelDocumentResponse _cancelDocument__return = port.cancelDocument(_cancelDocument_parameters);
        System.out.println("cancelDocument.result=" + _cancelDocument__return);


        }

        System.exit(0);
    }

}
