# OpenShift Deployment - SIPABWebService
# Este archivo contiene todos los recursos necesarios para deployar la aplicación
# Generado automáticamente para integración con OpenShift

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sipab-webservice
  labels:
    app: sipab-webservice
    version: "1.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sipab-webservice
  template:
    metadata:
      labels:
        app: sipab-webservice
    spec:
      containers:
      - name: sipab-webservice
        image: image-registry.openshift-image-registry.svc:5000/sipab-proyecto/sipab-webservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8181
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "openshift"
        - name: JAVA_OPTS
          value: "-Xms512m -Xmx1024m"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ORACLE_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: oracle-db-secret
              key: url
        - name: ORACLE_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: oracle-db-secret
              key: username
        - name: ORACLE_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: oracle-db-secret
              key: password
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8181
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8181
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1536Mi"
            cpu: "2000m"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000

---
apiVersion: v1
kind: Service
metadata:
  name: sipab-webservice
  labels:
    app: sipab-webservice
spec:
  type: ClusterIP
  ports:
  - port: 8181
    targetPort: 8181
    protocol: TCP
  selector:
    app: sipab-webservice

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sipab-webservice
  labels:
    app: sipab-webservice
spec:
  to:
    kind: Service
    name: sipab-webservice
  port:
    targetPort: 8181
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sipab-config
  labels:
    app: sipab-webservice
data:
  application.properties: |
    spring.application.name=SIPABWebService
    server.port=8181
    
    # Logging
    logging.level.root=INFO
    logging.level.mx.com.telcel.sipab=DEBUG
    
    # Actuator para health checks
    management.endpoints.web.exposure.include=health,info,metrics
    management.endpoint.health.probes.enabled=true
    management.endpoint.health.liveness-state.enabled=true
    management.endpoint.health.readiness-state.enabled=true
    
    # Configuración de integración con servicios externos
    integration.service.date-time.format=yyyy-MM-dd'T'HH:mm:ss.SSSXXX
    
    # CBS Configuration
    integration.service.cbs.headers.Bes-usuario=102
    integration.service.cbs.send-by=openshift-deployment
    
    # CRM Configuration
    integration.service.crm.headers.Client-Id=${CRM_CLIENT_ID}
    integration.service.crm.send-by=openshift-deployment
    
    # Interfaces Configuration
    integration.service.interfaces.headers.Client-Id=${INTERFACES_CLIENT_ID}
    integration.service.interfaces.send-by=openshift-deployment
    
    # ColdView Configuration
    integration.service.coldView.usuario=${COLDVIEW_USUARIO}
    integration.service.coldView.sistema=M
    integration.service.coldView.resourceConfig=cv_mobile

