kind: Deployment
apiVersion: apps/v1
metadata:
  name: sipab-webservice
  labels:
    app: sipab-webservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sipab-webservice
  template:
    metadata:
      labels:
        app: sipab-webservice
    spec:
      containers:
        - name: sipab-webservice
          image: sipab-webservice-image:latest
          ports:
            - name: http
              containerPort: 8181
              protocol: TCP
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: "openshift"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ORACLE_DATASOURCE_URL
            valueFrom:
              secretKeyRef:
                name: oracle-db-secret
                key: url
          - name: ORACLE_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: oracle-db-secret
                key: username
          - name: ORACLE_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: oracle-db-secret
                key: password
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8181
            initialDelaySeconds: 90
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8181
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1536Mi"
              cpu: "2000m"
---
kind: Service
apiVersion: v1
metadata:
  name: sipab-webservice-svc
  labels:
    app: sipab-webservice
spec:
  ports:
    - name: http-8181
      port: 8181
      protocol: TCP
      targetPort: 8181
  selector:
    app: sipab-webservice
