apiVersion: v1
kind: Secret
metadata:
  name: oracle-db-secret
  namespace: sipab4
type: Opaque
data:
  url: amRiYzpvcmFjbGU6dGhpbkAxMC4xOTEuMTA1LjE4OjE1NTAvbWJnd2Rlcw==
  username: TUJHV09XTg==
  password: c2VwdGVtYmVyIzEx
