package mx.com.telcel.sipab.constant;

public class QueryConstant {
	
	public static final String BUSCA_USUARIO = "SELECT * FROM (\r\n"
			+ "	SELECT NUMERO_EMPLEADO,ID_CENTRO,ID_ROL,ID_REGION,ID_PUESTO,CVE_USUARIO,NOMBRE,\r\n"
			+ "		ESTATUS,CORREO,ULTIMO_ACCESO,EMPLEADO_MODIFICA,FECHA_MODIFICA,ESTATUS_SESION,\r\n"
			+ "		(NUMERO_EMPLEADO||' '||CVE_USUARIO||' '||NOMBRE||' '||CORREO) AS SELECTIVIDAD\r\n"
			+ "	FROM SIPAB4_USUARIOS\r\n"
			+ "	WHERE ESTATUS IN ('A', 'I')\r\n"
			+ "	ORDER BY NUMERO_EMPLEADO\r\n"
			+ ") USUARIOS\r\n"
			+ "WHERE 1 = 1\r\n"
			+ "AND TRANSLATE( \r\n"
			+ "	UPPER(USUARIOS.SELECTIVIDAD), 'ÁÉÍÓÚÀÈÌÒÙÄËÏÖÜÂÊÎÔÛ', 'AEIOUAEIOUAEIOUAEIOU'\r\n"
			+ ") \r\n"
			+ "LIKE '%' || TRANSLATE(UPPER(TRIM(:clave1)),'ÁÉÍÓÚÀÈÌÒÙÄËÏÖÜÂÊÎÔÛ', 'AEIOUAEIOUAEIOUAEIOU') || '%'\r\n"
			+ "AND TRANSLATE( \r\n"
			+ "	UPPER(USUARIOS.SELECTIVIDAD), 'ÁÉÍÓÚÀÈÌÒÙÄËÏÖÜÂÊÎÔÛ', 'AEIOUAEIOUAEIOUAEIOU'\r\n"
			+ ") \r\n"
			+ "LIKE '%' || TRANSLATE(UPPER(TRIM(:clave2)),'ÁÉÍÓÚÀÈÌÒÙÄËÏÖÜÂÊÎÔÛ', 'AEIOUAEIOUAEIOUAEIOU') || '%'\r\n"
			+ "AND TRANSLATE( \r\n"
			+ "	UPPER(USUARIOS.SELECTIVIDAD), 'ÁÉÍÓÚÀÈÌÒÙÄËÏÖÜÂÊÎÔÛ', 'AEIOUAEIOUAEIOUAEIOU'\r\n"
			+ ") \r\n"
			+ "LIKE '%' || TRANSLATE(UPPER(TRIM(:clave3)),'ÁÉÍÓÚÀÈÌÒÙÄËÏÖÜÂÊÎÔÛ', 'AEIOUAEIOUAEIOUAEIOU') || '%'\r\n"
			+ "AND TRANSLATE( \r\n"
			+ "	UPPER(USUARIOS.SELECTIVIDAD), 'ÁÉÍÓÚÀÈÌÒÙÄËÏÖÜÂÊÎÔÛ', 'AEIOUAEIOUAEIOUAEIOU'\r\n"
			+ ") \r\n"
			+ "LIKE '%' || TRANSLATE(UPPER(TRIM(:clave4)),'ÁÉÍÓÚÀÈÌÒÙÄËÏÖÜÂÊÎÔÛ', 'AEIOUAEIOUAEIOUAEIOU') || '%'";
	
	public static final String MAX_ID_DETALLE_TRAMITE = "SELECT MAX(ID_DETALLE_TRAMITE)+1 FROM SIPAB4_TRAMITES_DETALLE";
	
	public static final String MAX_ID_DETALLE_TRAMITE_POR_FOLIO = "SELECT MAX(ID_DETALLE_TRAMITE) FROM SIPAB4_TRAMITES_DETALLE TD\r\n"
			+ "WHERE FOLIO = :folio AND ANIO = :anio";
	
	public static final String USO_CFDI_POR_REGIMEN = "SELECT DISTINCT U.USO_CFDI, U.DESCRIPCION, U.FISICA, U.MORAL, U.ID_USO_CFDI \r\n"
			+ "FROM SIPAB_C_USO_CFDI U \r\n"
			+ "INNER JOIN SIPAB_C_REG_FIS_USO_CFDI RU ON (RU.ID_USO_CFDI = U.ID_USO_CFDI)\r\n"
			+ "INNER JOIN SIPAB_C_REGIMEN_FISCAL R ON (RU.ID_REGIMEN_FISCAL = R.ID_REGIMEN_FISCAL) \r\n"
			+ "WHERE R.ID_REGIMEN_FISCAL = :idRegimen AND U.FISICA = :fisica AND U.MORAL = :moral \r\n"
			+ "ORDER BY u.ID_USO_CFDI";
	
	public static final String CENTRO_COSTOS_POR_GERENCIA = "SELECT DISTINCT C.ID_CENTRO, C.ID_GRUPO, C.ID_REGION, C.DESC_CENTRO, C.PREFIJO, \r\n"
			+ "	C.ESTATUS, C.ID_GERENCIA, C.ID_SUBDIRECCION, C.ID_DIRECCION ,U.NOMBRE \r\n"
			+ "	FROM \r\n"
			+ "		(SELECT ID_CENTRO, ID_GRUPO, ID_REGION, DESC_CENTRO, PREFIJO, \r\n"
			+ "			ESTATUS, ID_GERENCIA, ID_SUBDIRECCION, ID_DIRECCION \r\n"
			+ "		FROM SIPAB4_CENTRO_COSTOS \r\n"
			+ "		WHERE (ID_GERENCIA = :idGerencia /*OR ID_SUBDIRECCION = :idGerencia OR ID_GERENCIA = :idGerencia*/) \r\n"
			+ "			AND	ESTATUS = 'A') C \r\n"
			+ "		LEFT JOIN SIPAB4_USUARIOS U ON C.ID_CENTRO = U.ID_CENTRO ANd U.ID_PUESTO = 3 AND U.ESTATUS='A'  \r\n"
			+ "		ORDER BY C.DESC_CENTRO";
	
	public static final String TRAMITE_ACTIVO_POR_UUID = "SELECT C.FOLIO, C.ANIO, C.ID_ESTATUS_CANCELACION, C.ID_ESTATUS_COMPLEMENTO, \r\n"
			+ "	C.ID_CLAVE_BATCH_EGR, C.ID_CLAVE_BATCH_ING, C.FECHA_FACTURA, C.UUID, \r\n"
			+ "	C.FACTURA_PAGADA, C.TIPO_CANCELACION, C.IMPRESORA_SAP \r\n"
			+ "FROM SIPAB4_TRAMITES T \r\n"
			+ "INNER JOIN SIPAB4_CANCELACION_CFDI C ON (T.FOLIO = C.FOLIO AND T.ANIO = C. ANIO) \r\n"
			+ "WHERE T.ID_ESTATUS NOT IN (2,4,7,12,36) AND C.UUID = :uuid";
	
	public static final String CLAVES_SAP = "SELECT CS.ID_CLAVE_SAP, CS.ID_SECTOR, CS.ID_ORIGEN_PAGOS, CS.ID_SECCION, \r\n"
			+ "	CS.CLAVE_SAP, CS.DESCRIPCION, CS.TRAMITE, CS.PLATAFORMA, CS.IEPS, \r\n"
			+ "	CS.CUENTA_CONTABLE, CS.CUENTA_IEPS, CS.VERSION_SAP, CS.ESTATUS, 0 AS ID_CLAVE_BATCH, O.ORIGEN_LARGO AS CLAVE_BATCH\r\n"
			+ "FROM SIPAB4_CLAVES_SAP CS \r\n"
			+ "INNER JOIN SIPAB4_ORIGENES_PAGO OP ON CS.ID_ORIGEN_PAGOS = OP.ID_ORIGEN_PAGOS \r\n"
			+ "WHERE OP.ID_REGION = :idRegion \r\n"
			+ "	AND OP.ORIGEN_CORTO = 'BES' \r\n"
			+ "	AND op.ORIGEN = 'SAP' \r\n"
			+ "	AND CS.TRAMITE = :tramite";
	
	public static final String CLAVES_SAP_SINVALIDACION = "SELECT CS.ID_CLAVE_SAP, CS.ID_SECTOR, CS.ID_ORIGEN_PAGOS, CS.ID_SECCION, \r\n"
			+ "	CS.CLAVE_SAP, CS.DESCRIPCION, CS.TRAMITE, CS.PLATAFORMA, CS.IEPS, \r\n"
			+ "	CS.CUENTA_CONTABLE, CS.CUENTA_IEPS, CS.VERSION_SAP, CS.ESTATUS, 0 AS ID_CLAVE_BATCH, O.ORIGEN_LARGO AS CLAVE_BATCH \r\n"
			+ "FROM SIPAB4_CLAVES_SAP CS \r\n"
			+ "JOIN SIPAB4_ORIGENES_PAGO O ON (CS.ID_ORIGEN_PAGOS = O.ID_ORIGEN_PAGOS) \r\n"
			+ "WHERE TRIM(TRAMITE) = :tramite \r\n"
			+ "	AND ID_SECTOR = (SELECT ID_SECTOR FROM SIPAB4_CLAVES_SECTOR WHERE DETALLE_SECTOR LIKE :sector) \r\n"
			+ "	AND TRIM(PLATAFORMA) LIKE :plataforma \r\n"
			+ "	AND TRIM(ESTATUS) = 'A' \r\n"
			+ "	AND VERSION_SAP = (SELECT TRIM(VALOR) FROM SIPAB4_PARAMETROS WHERE CVE_PARAMETRO = 'CVE_SAP_ACTIVA') \r\n"
			+ "ORDER BY CS.DESCRIPCION";
	
	public static final String CLAVES_SAP_POR_SECTOR = "SELECT ID_CLAVE_SAP, CS.ID_SECTOR, CS.ID_ORIGEN_PAGOS, CS.ID_SECCION, \r\n"
			+ "	CS.CLAVE_SAP, CS.DESCRIPCION, CS.TRAMITE, CS.PLATAFORMA, CS.IEPS, \r\n"
			+ "	CS.CUENTA_CONTABLE, CS.CUENTA_IEPS, CS.VERSION_SAP, CS.ESTATUS, BATCH.ID_CLAVE_BATCH, BATCH.CLAVE_BATCH \r\n"
			+ "FROM SIPAB4_CLAVES_SAP CS \r\n"
			+ "JOIN SIPAB4_CLAVES_SECTOR SEC ON (CS.ID_SECTOR = SEC.ID_SECTOR) \r\n"
			+ "JOIN SIPAB4_CLAVES_BATCH BATCH ON (BATCH.ID_CONCEPTO = CS.ID_SECCION AND CS.ID_SECCION > 0 AND CS.TRAMITE = 'NCA') \r\n"
			+ "WHERE SEC.ID_SECTOR = :idSector \r\n"
			+ "	AND CS.ESTATUS = 'A' \r\n"
			+ "ORDER BY CS.DESCRIPCION";
	
	public static final String CONCEPTOS_POR_TRAMITE = "SELECT C.ID_CONCEPTO, C.DESC_CONCEPTO, C.TRAMITE, C.ESTATUS, C.PLATAFORMA, \r\n"
			+ "	CB.ID_CLAVE_BATCH \r\n"
			+ "FROM SIPAB4_CONCEPTOS C \r\n"
			+ "INNER JOIN SIPAB4_CLAVES_BATCH CB ON (C.ID_CONCEPTO = CB.ID_CONCEPTO) \r\n"
			+ "WHERE C.TRAMITE LIKE :tramite AND C.PLATAFORMA = 'BES' \r\n"
			+ "	AND C.ESTATUS = 'A' AND C.DESC_CONCEPTO NOT LIKE '%INTER%' \r\n"
			+ "ORDER BY C.DESC_CONCEPTO";
	
	public static final String CONCEPTOS_POR_TRAMITE_Y_REGIONES = "SELECT C.ID_CONCEPTO, C.DESC_CONCEPTO, C.TRAMITE, C.ESTATUS, C.PLATAFORMA, \r\n"
			+ "	CB.ID_CLAVE_BATCH \r\n"
			+ "FROM SIPAB4_CONCEPTOS C \r\n"
			+ "INNER JOIN SIPAB4_CLAVES_BATCH CB ON (C.ID_CONCEPTO = CB.ID_CONCEPTO) \r\n"
			+ "WHERE C.TRAMITE LIKE :tramite AND CB.ID_REGION_CUENTA = :regionCuenta AND CB.ID_REGION_USUARIO = :regionUsuario \r\n"
			+ "	AND C.ESTATUS = 'A' AND C.DESC_CONCEPTO NOT LIKE '%INTER%' \r\n"
			+ "ORDER BY C.DESC_CONCEPTO";
	
	public static final String CONCEPTOS_TIPO_NOTA = "SELECT C.ID_CONCEPTO, C.DESC_CONCEPTO, C.TRAMITE, C.ESTATUS, C.PLATAFORMA, \r\n"
			+ "	cb.ID_CLAVE_BATCH \r\n"
			+ "FROM  SIPAB4_CONCEPTOS c \r\n"
			+ "INNER JOIN SIPAB4_CLAVES_BATCH cb ON c.ID_CONCEPTO = cb.ID_CONCEPTO \r\n"
			+ "WHERE c.TRAMITE LIKE 'FIANZ' AND C.PLATAFORMA = 'BES' \r\n"
			+ "	AND c.ESTATUS = 'A'\r\n "
			+ "ORDER BY c.DESC_CONCEPTO";
	
	public static final String CONCEPTOS_FIA = "SELECT C.ID_CONCEPTO, C.DESC_CONCEPTO, C.TRAMITE, C.ESTATUS, C.PLATAFORMA, \r\n"
			+ "	0 AS ID_CLAVE_BATCH \r\n"
			+ " FROM SIPAB4_CONCEPTOS C WHERE C.TRAMITE = 'FIANZ' AND C.ESTATUS = 'A' AND C.DESC_CONCEPTO LIKE 'Cliente%'";
	
	public static final String MAX_ID_SIDES = "SELECT MAX(ID_NOTA_SIDES) + 1 FROM SIPAB4_SIDES";

}
