
package mx.com.telcel.sipab.client.interfaces;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-10-24T12:33:26.080-06:00
 * Generated source version: 4.0.3
 *
 */
public final class TelcelInterfaceServices_TelcelInterfaceServicesHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", "TelcelInterfaceServicesHttpService");

    private TelcelInterfaceServices_TelcelInterfaceServicesHttpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TelcelInterfaceServicesHttpService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        TelcelInterfaceServicesHttpService ss = new TelcelInterfaceServicesHttpService(wsdlURL, SERVICE_NAME);
        TelcelInterfaceServices port = ss.getTelcelInterfaceServicesHttpPort();

        {
        System.out.println("Invoking notifyFinalDeliveryStatus...");
        mx.com.telcel.sipab.client.interfaces.NotifyFinalDeliveryStatus _notifyFinalDeliveryStatus_notifyFinalDeliveryStatusRequest = new mx.com.telcel.sipab.client.interfaces.NotifyFinalDeliveryStatus();
        try {
            mx.com.telcel.sipab.client.interfaces.NotifyFinalDeliveryStatusResponse _notifyFinalDeliveryStatus__return = port.notifyFinalDeliveryStatus(_notifyFinalDeliveryStatus_notifyFinalDeliveryStatusRequest);
            System.out.println("notifyFinalDeliveryStatus.result=" + _notifyFinalDeliveryStatus__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking stockIn...");
        mx.com.telcel.sipab.client.interfaces.StockIn _stockIn_stockInRequest = new mx.com.telcel.sipab.client.interfaces.StockIn();
        try {
            mx.com.telcel.sipab.client.interfaces.StockInResponse _stockIn__return = port.stockIn(_stockIn_stockInRequest);
            System.out.println("stockIn.result=" + _stockIn__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking recibirResultado...");
        mx.com.telcel.sipab.client.interfaces.RecibirResultado _recibirResultado_recibirResultadoRequest = new mx.com.telcel.sipab.client.interfaces.RecibirResultado();
        try {
            mx.com.telcel.sipab.client.interfaces.RecibirResultadoResponse _recibirResultado__return = port.recibirResultado(_recibirResultado_recibirResultadoRequest);
            System.out.println("recibirResultado.result=" + _recibirResultado__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getCustByRFC4CreditCheck...");
        mx.com.telcel.sipab.client.interfaces.GetCustByRFC4CreditCheck _getCustByRFC4CreditCheck_getCustByRFC4CreditCheckRequest = new mx.com.telcel.sipab.client.interfaces.GetCustByRFC4CreditCheck();
        try {
            mx.com.telcel.sipab.client.interfaces.GetCustByRFC4CreditCheckResponse _getCustByRFC4CreditCheck__return = port.getCustByRFC4CreditCheck(_getCustByRFC4CreditCheck_getCustByRFC4CreditCheckRequest);
            System.out.println("getCustByRFC4CreditCheck.result=" + _getCustByRFC4CreditCheck__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking specialChangeOffering...");
        mx.com.telcel.sipab.client.interfaces.SpecialChangeOffering _specialChangeOffering_specialChangeOfferingRequest = new mx.com.telcel.sipab.client.interfaces.SpecialChangeOffering();
        try {
            mx.com.telcel.sipab.client.interfaces.SpecialChangeOfferingResponse _specialChangeOffering__return = port.specialChangeOffering(_specialChangeOffering_specialChangeOfferingRequest);
            System.out.println("specialChangeOffering.result=" + _specialChangeOffering__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking queryDictItems...");
        mx.com.telcel.sipab.client.interfaces.QueryDictItems _queryDictItems_queryDictItemsRequest = new mx.com.telcel.sipab.client.interfaces.QueryDictItems();
        try {
            mx.com.telcel.sipab.client.interfaces.QueryDictItemsResponse _queryDictItems__return = port.queryDictItems(_queryDictItems_queryDictItemsRequest);
            System.out.println("queryDictItems.result=" + _queryDictItems__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking changeSubsPayMode...");
        mx.com.telcel.sipab.client.interfaces.ChangeSubsPayMode _changeSubsPayMode_changeSubsPayModeRequest = new mx.com.telcel.sipab.client.interfaces.ChangeSubsPayMode();
        try {
            mx.com.telcel.sipab.client.interfaces.ChangeSubsPayModeResponse _changeSubsPayMode__return = port.changeSubsPayMode(_changeSubsPayMode_changeSubsPayModeRequest);
            System.out.println("changeSubsPayMode.result=" + _changeSubsPayMode__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getProfileSVA...");
        mx.com.telcel.sipab.client.interfaces.GetProfileSVA _getProfileSVA_getProfileSVARequest = new mx.com.telcel.sipab.client.interfaces.GetProfileSVA();
        try {
            mx.com.telcel.sipab.client.interfaces.GetProfileSVAResponse _getProfileSVA__return = port.getProfileSVA(_getProfileSVA_getProfileSVARequest);
            System.out.println("getProfileSVA.result=" + _getProfileSVA__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking queryFnF...");
        mx.com.telcel.sipab.client.interfaces.QueryFnF _queryFnF_queryFnFRequest = new mx.com.telcel.sipab.client.interfaces.QueryFnF();
        try {
            mx.com.telcel.sipab.client.interfaces.QueryFnFResponse _queryFnF__return = port.queryFnF(_queryFnF_queryFnFRequest);
            System.out.println("queryFnF.result=" + _queryFnF__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking activateOfferingBySubscriber...");
        mx.com.telcel.sipab.client.interfaces.ActivateOfferingBySubscriber _activateOfferingBySubscriber_activateOfferingBySubscriberRequest = new mx.com.telcel.sipab.client.interfaces.ActivateOfferingBySubscriber();
        try {
            mx.com.telcel.sipab.client.interfaces.ActivateOfferingBySubscriberResponse _activateOfferingBySubscriber__return = port.activateOfferingBySubscriber(_activateOfferingBySubscriber_activateOfferingBySubscriberRequest);
            System.out.println("activateOfferingBySubscriber.result=" + _activateOfferingBySubscriber__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking generateDeposit...");
        mx.com.telcel.sipab.client.interfaces.GenerateDeposit _generateDeposit_generateDepositRequest = new mx.com.telcel.sipab.client.interfaces.GenerateDeposit();
        try {
            mx.com.telcel.sipab.client.interfaces.GenerateDepositResponse _generateDeposit__return = port.generateDeposit(_generateDeposit_generateDepositRequest);
            System.out.println("generateDeposit.result=" + _generateDeposit__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking querySysParam...");
        mx.com.telcel.sipab.client.interfaces.QuerySysParam _querySysParam_querySysParamRequest = new mx.com.telcel.sipab.client.interfaces.QuerySysParam();
        try {
            mx.com.telcel.sipab.client.interfaces.QuerySysParamResponse _querySysParam__return = port.querySysParam(_querySysParam_querySysParamRequest);
            System.out.println("querySysParam.result=" + _querySysParam__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking modifyCustInfoForDOL...");
        mx.com.telcel.sipab.client.interfaces.ModifyCustInfoForDOL _modifyCustInfoForDOL_modifyCustInfoForDOLRequest = new mx.com.telcel.sipab.client.interfaces.ModifyCustInfoForDOL();
        try {
            mx.com.telcel.sipab.client.interfaces.ModifyCustInfoForDOLResponse _modifyCustInfoForDOL__return = port.modifyCustInfoForDOL(_modifyCustInfoForDOL_modifyCustInfoForDOLRequest);
            System.out.println("modifyCustInfoForDOL.result=" + _modifyCustInfoForDOL__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking changePriOfferingNew...");
        mx.com.telcel.sipab.client.interfaces.ChangePriOfferingNew _changePriOfferingNew_changePriOfferingNewRequest = new mx.com.telcel.sipab.client.interfaces.ChangePriOfferingNew();
        try {
            mx.com.telcel.sipab.client.interfaces.ChangePriOfferingNewResponse _changePriOfferingNew__return = port.changePriOfferingNew(_changePriOfferingNew_changePriOfferingNewRequest);
            System.out.println("changePriOfferingNew.result=" + _changePriOfferingNew__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getProductSVA...");
        mx.com.telcel.sipab.client.interfaces.GetProductSVA _getProductSVA_getProductSVARequest = new mx.com.telcel.sipab.client.interfaces.GetProductSVA();
        try {
            mx.com.telcel.sipab.client.interfaces.GetProductSVAResponse _getProductSVA__return = port.getProductSVA(_getProductSVA_getProductSVARequest);
            System.out.println("getProductSVA.result=" + _getProductSVA__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking validateToken...");
        mx.com.telcel.sipab.client.interfaces.ValidateToken _validateToken_validateTokenRequest = new mx.com.telcel.sipab.client.interfaces.ValidateToken();
        try {
            mx.com.telcel.sipab.client.interfaces.ValidateTokenResponse _validateToken__return = port.validateToken(_validateToken_validateTokenRequest);
            System.out.println("validateToken.result=" + _validateToken__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking queryCustResourceDealType...");
        mx.com.telcel.sipab.client.interfaces.QueryCustResourceDealType _queryCustResourceDealType_queryCustResourceDealTypeRequest = new mx.com.telcel.sipab.client.interfaces.QueryCustResourceDealType();
        try {
            mx.com.telcel.sipab.client.interfaces.QueryCustResourceDealTypeResponse _queryCustResourceDealType__return = port.queryCustResourceDealType(_queryCustResourceDealType_queryCustResourceDealTypeRequest);
            System.out.println("queryCustResourceDealType.result=" + _queryCustResourceDealType__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking queryAvailableBillCycles...");
        mx.com.telcel.sipab.client.interfaces.QueryAvailableBillCycles _queryAvailableBillCycles_queryAvailableBillCyclesRequest = new mx.com.telcel.sipab.client.interfaces.QueryAvailableBillCycles();
        try {
            mx.com.telcel.sipab.client.interfaces.QueryAvailableBillCyclesResponse _queryAvailableBillCycles__return = port.queryAvailableBillCycles(_queryAvailableBillCycles_queryAvailableBillCyclesRequest);
            System.out.println("queryAvailableBillCycles.result=" + _queryAvailableBillCycles__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking supplementIndividualCust...");
        mx.com.telcel.sipab.client.interfaces.SupplementIndividualCust _supplementIndividualCust_supplementIndividualCustRequest = new mx.com.telcel.sipab.client.interfaces.SupplementIndividualCust();
        try {
            mx.com.telcel.sipab.client.interfaces.SupplementIndividualCustResponse _supplementIndividualCust__return = port.supplementIndividualCust(_supplementIndividualCust_supplementIndividualCustRequest);
            System.out.println("supplementIndividualCust.result=" + _supplementIndividualCust__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking lockOrUnlockIMEIService...");
        mx.com.telcel.sipab.client.interfaces.LockOrUnlockIMEIService _lockOrUnlockIMEIService_lockOrUnlockIMEIServiceRequest = new mx.com.telcel.sipab.client.interfaces.LockOrUnlockIMEIService();
        try {
            mx.com.telcel.sipab.client.interfaces.LockOrUnlockIMEIServiceResponse _lockOrUnlockIMEIService__return = port.lockOrUnlockIMEIService(_lockOrUnlockIMEIService_lockOrUnlockIMEIServiceRequest);
            System.out.println("lockOrUnlockIMEIService.result=" + _lockOrUnlockIMEIService__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking queryIMEI...");
        mx.com.telcel.sipab.client.interfaces.QueryIMEI _queryIMEI_queryIMEIRequest = new mx.com.telcel.sipab.client.interfaces.QueryIMEI();
        try {
            mx.com.telcel.sipab.client.interfaces.QueryIMEIResponse _queryIMEI__return = port.queryIMEI(_queryIMEI_queryIMEIRequest);
            System.out.println("queryIMEI.result=" + _queryIMEI__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking queryIoTdevice...");
        mx.com.telcel.sipab.client.interfaces.QueryIoTdevice _queryIoTdevice_queryIoTdeviceRequest = new mx.com.telcel.sipab.client.interfaces.QueryIoTdevice();
        try {
            mx.com.telcel.sipab.client.interfaces.QueryIoTdeviceResponse _queryIoTdevice__return = port.queryIoTdevice(_queryIoTdevice_queryIoTdeviceRequest);
            System.out.println("queryIoTdevice.result=" + _queryIoTdevice__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking updateInvResourceInfo...");
        mx.com.telcel.sipab.client.interfaces.UpdateInvResourceInfo _updateInvResourceInfo_updateInvResourceInfoRequest = new mx.com.telcel.sipab.client.interfaces.UpdateInvResourceInfo();
        try {
            mx.com.telcel.sipab.client.interfaces.UpdateInvResourceInfoResponse _updateInvResourceInfo__return = port.updateInvResourceInfo(_updateInvResourceInfo_updateInvResourceInfoRequest);
            System.out.println("updateInvResourceInfo.result=" + _updateInvResourceInfo__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking calcPenalty...");
        mx.com.telcel.sipab.client.interfaces.CalcPenalty _calcPenalty_calcPenaltyRequest = new mx.com.telcel.sipab.client.interfaces.CalcPenalty();
        try {
            mx.com.telcel.sipab.client.interfaces.CalcPenaltyResponse _calcPenalty__return = port.calcPenalty(_calcPenalty_calcPenaltyRequest);
            System.out.println("calcPenalty.result=" + _calcPenalty__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking createGroupCustomer...");
        mx.com.telcel.sipab.client.interfaces.CreateGroupCustomer _createGroupCustomer_createGroupCustomerRequest = new mx.com.telcel.sipab.client.interfaces.CreateGroupCustomer();
        try {
            mx.com.telcel.sipab.client.interfaces.CreateGroupCustomerResponse _createGroupCustomer__return = port.createGroupCustomer(_createGroupCustomer_createGroupCustomerRequest);
            System.out.println("createGroupCustomer.result=" + _createGroupCustomer__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getSubsCustAcctBasicInfo...");
        mx.com.telcel.sipab.client.interfaces.GetSubsCustAcctBasicInfo _getSubsCustAcctBasicInfo_getSubsCustAcctBasicInfoRequest = new mx.com.telcel.sipab.client.interfaces.GetSubsCustAcctBasicInfo();
        try {
            mx.com.telcel.sipab.client.interfaces.GetSubsCustAcctBasicInfoResponse _getSubsCustAcctBasicInfo__return = port.getSubsCustAcctBasicInfo(_getSubsCustAcctBasicInfo_getSubsCustAcctBasicInfoRequest);
            System.out.println("getSubsCustAcctBasicInfo.result=" + _getSubsCustAcctBasicInfo__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking sendIMEINote...");
        mx.com.telcel.sipab.client.interfaces.SendIMEINote _sendIMEINote_sendIMEINoteRequest = new mx.com.telcel.sipab.client.interfaces.SendIMEINote();
        try {
            mx.com.telcel.sipab.client.interfaces.SendIMEINoteResponse _sendIMEINote__return = port.sendIMEINote(_sendIMEINote_sendIMEINoteRequest);
            System.out.println("sendIMEINote.result=" + _sendIMEINote__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking queryAvailableAccounts...");
        mx.com.telcel.sipab.client.interfaces.QueryAvailableAccounts _queryAvailableAccounts_queryAvailableAccountsRequest = new mx.com.telcel.sipab.client.interfaces.QueryAvailableAccounts();
        try {
            mx.com.telcel.sipab.client.interfaces.QueryAvailableAccountsResponse _queryAvailableAccounts__return = port.queryAvailableAccounts(_queryAvailableAccounts_queryAvailableAccountsRequest);
            System.out.println("queryAvailableAccounts.result=" + _queryAvailableAccounts__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking returnResource...");
        mx.com.telcel.sipab.client.interfaces.ReturnResource _returnResource_returnResourceRequest = new mx.com.telcel.sipab.client.interfaces.ReturnResource();
        try {
            mx.com.telcel.sipab.client.interfaces.ReturnResourceResponse _returnResource__return = port.returnResource(_returnResource_returnResourceRequest);
            System.out.println("returnResource.result=" + _returnResource__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking validateCPO2Platino...");
        mx.com.telcel.sipab.client.interfaces.ValidateCPO2Platino _validateCPO2Platino_validateCPO2PlatinoRequest = new mx.com.telcel.sipab.client.interfaces.ValidateCPO2Platino();
        try {
            mx.com.telcel.sipab.client.interfaces.ValidateCPO2PlatinoResponse _validateCPO2Platino__return = port.validateCPO2Platino(_validateCPO2Platino_validateCPO2PlatinoRequest);
            System.out.println("validateCPO2Platino.result=" + _validateCPO2Platino__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking batchCreateNewSub...");
        mx.com.telcel.sipab.client.interfaces.BatchCreateNewSub _batchCreateNewSub_batchCreateNewSubRequest = new mx.com.telcel.sipab.client.interfaces.BatchCreateNewSub();
        try {
            mx.com.telcel.sipab.client.interfaces.BatchCreateNewSubResponse _batchCreateNewSub__return = port.batchCreateNewSub(_batchCreateNewSub_batchCreateNewSubRequest);
            System.out.println("batchCreateNewSub.result=" + _batchCreateNewSub__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking reserveBusiness...");
        mx.com.telcel.sipab.client.interfaces.ReserveBusiness _reserveBusiness_reserveBusinessRequest = new mx.com.telcel.sipab.client.interfaces.ReserveBusiness();
        try {
            mx.com.telcel.sipab.client.interfaces.ReserveBusinessResponse _reserveBusiness__return = port.reserveBusiness(_reserveBusiness_reserveBusinessRequest);
            System.out.println("reserveBusiness.result=" + _reserveBusiness__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getOrderDetailInfo...");
        mx.com.telcel.sipab.client.interfaces.GetOrderDetailInfo _getOrderDetailInfo_getOrderDetailInfoRequest = new mx.com.telcel.sipab.client.interfaces.GetOrderDetailInfo();
        try {
            mx.com.telcel.sipab.client.interfaces.GetOrderDetailInfoResponse _getOrderDetailInfo__return = port.getOrderDetailInfo(_getOrderDetailInfo_getOrderDetailInfoRequest);
            System.out.println("getOrderDetailInfo.result=" + _getOrderDetailInfo__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking queryInsuranceOffer...");
        mx.com.telcel.sipab.client.interfaces.QueryInsuranceOffer _queryInsuranceOffer_queryInsuranceOfferRequest = new mx.com.telcel.sipab.client.interfaces.QueryInsuranceOffer();
        try {
            mx.com.telcel.sipab.client.interfaces.QueryInsuranceOfferResponse _queryInsuranceOffer__return = port.queryInsuranceOffer(_queryInsuranceOffer_queryInsuranceOfferRequest);
            System.out.println("queryInsuranceOffer.result=" + _queryInsuranceOffer__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking changeRegion...");
        mx.com.telcel.sipab.client.interfaces.ChangeRegion _changeRegion_changeRegionRequest = new mx.com.telcel.sipab.client.interfaces.ChangeRegion();
        try {
            mx.com.telcel.sipab.client.interfaces.ChangeRegionResponse _changeRegion__return = port.changeRegion(_changeRegion_changeRegionRequest);
            System.out.println("changeRegion.result=" + _changeRegion__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking crmRechargeRollBack...");
        mx.com.telcel.sipab.client.interfaces.CrmRechargeRollBack _crmRechargeRollBack_crmRechargeRollBackRequest = new mx.com.telcel.sipab.client.interfaces.CrmRechargeRollBack();
        try {
            mx.com.telcel.sipab.client.interfaces.CrmRechargeRollBackResponse _crmRechargeRollBack__return = port.crmRechargeRollBack(_crmRechargeRollBack_crmRechargeRollBackRequest);
            System.out.println("crmRechargeRollBack.result=" + _crmRechargeRollBack__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getBatchFile...");
        mx.com.telcel.sipab.client.interfaces.GetBatchFile _getBatchFile_getBatchFileRequest = new mx.com.telcel.sipab.client.interfaces.GetBatchFile();
        try {
            mx.com.telcel.sipab.client.interfaces.GetBatchFileResponse _getBatchFile__return = port.getBatchFile(_getBatchFile_getBatchFileRequest);
            System.out.println("getBatchFile.result=" + _getBatchFile__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getOrders...");
        mx.com.telcel.sipab.client.interfaces.GetOrders _getOrders_getOrdersRequest = new mx.com.telcel.sipab.client.interfaces.GetOrders();
        try {
            mx.com.telcel.sipab.client.interfaces.GetOrdersResponse _getOrders__return = port.getOrders(_getOrders_getOrdersRequest);
            System.out.println("getOrders.result=" + _getOrders__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking validateCard...");
        mx.com.telcel.sipab.client.interfaces.ValidateCard _validateCard_validateCardRequest = new mx.com.telcel.sipab.client.interfaces.ValidateCard();
        try {
            mx.com.telcel.sipab.client.interfaces.ValidateCardResponse _validateCard__return = port.validateCard(_validateCard_validateCardRequest);
            System.out.println("validateCard.result=" + _validateCard__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking previewEarlyPay...");
        mx.com.telcel.sipab.client.interfaces.PreviewEarlyPay _previewEarlyPay_previewEarlyPayRequest = new mx.com.telcel.sipab.client.interfaces.PreviewEarlyPay();
        try {
            mx.com.telcel.sipab.client.interfaces.PreviewEarlyPayResponse _previewEarlyPay__return = port.previewEarlyPay(_previewEarlyPay_previewEarlyPayRequest);
            System.out.println("previewEarlyPay.result=" + _previewEarlyPay__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking actualizarHandsetStatus...");
        mx.com.telcel.sipab.client.interfaces.ActualizarHandsetStatus _actualizarHandsetStatus_actualizarHandsetStatusRequest = new mx.com.telcel.sipab.client.interfaces.ActualizarHandsetStatus();
        try {
            mx.com.telcel.sipab.client.interfaces.ActualizarHandsetStatusResponse _actualizarHandsetStatus__return = port.actualizarHandsetStatus(_actualizarHandsetStatus_actualizarHandsetStatusRequest);
            System.out.println("actualizarHandsetStatus.result=" + _actualizarHandsetStatus__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking swapResource...");
        mx.com.telcel.sipab.client.interfaces.SwapResource _swapResource_swapResourceRequest = new mx.com.telcel.sipab.client.interfaces.SwapResource();
        try {
            mx.com.telcel.sipab.client.interfaces.SwapResourceResponse _swapResource__return = port.swapResource(_swapResource_swapResourceRequest);
            System.out.println("swapResource.result=" + _swapResource__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking manageFnF...");
        mx.com.telcel.sipab.client.interfaces.ManageFnF _manageFnF_manageFnFRequest = new mx.com.telcel.sipab.client.interfaces.ManageFnF();
        try {
            mx.com.telcel.sipab.client.interfaces.ManageFnFResponse _manageFnF__return = port.manageFnF(_manageFnF_manageFnFRequest);
            System.out.println("manageFnF.result=" + _manageFnF__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking queryEntityRelations...");
        mx.com.telcel.sipab.client.interfaces.QueryEntityRelations _queryEntityRelations_queryEntityRelationsRequest = new mx.com.telcel.sipab.client.interfaces.QueryEntityRelations();
        try {
            mx.com.telcel.sipab.client.interfaces.QueryEntityRelationsResponse _queryEntityRelations__return = port.queryEntityRelations(_queryEntityRelations_queryEntityRelationsRequest);
            System.out.println("queryEntityRelations.result=" + _queryEntityRelations__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking querySubsServiceContract...");
        mx.com.telcel.sipab.client.interfaces.QuerySubsServiceContract _querySubsServiceContract_querySubsServiceContractRequest = new mx.com.telcel.sipab.client.interfaces.QuerySubsServiceContract();
        try {
            mx.com.telcel.sipab.client.interfaces.QuerySubsServiceContractResponse _querySubsServiceContract__return = port.querySubsServiceContract(_querySubsServiceContract_querySubsServiceContractRequest);
            System.out.println("querySubsServiceContract.result=" + _querySubsServiceContract__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking padrinoZeekMiAutoRegistration...");
        mx.com.telcel.sipab.client.interfaces.PadrinoZeekMiAutoRegistration _padrinoZeekMiAutoRegistration_padrinoZeekMiAutoRegistrationRequest = new mx.com.telcel.sipab.client.interfaces.PadrinoZeekMiAutoRegistration();
        try {
            mx.com.telcel.sipab.client.interfaces.PadrinoZeekMiAutoRegistrationResponse _padrinoZeekMiAutoRegistration__return = port.padrinoZeekMiAutoRegistration(_padrinoZeekMiAutoRegistration_padrinoZeekMiAutoRegistrationRequest);
            System.out.println("padrinoZeekMiAutoRegistration.result=" + _padrinoZeekMiAutoRegistration__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking queryComments...");
        mx.com.telcel.sipab.client.interfaces.QueryComments _queryComments_queryCommentsRequest = new mx.com.telcel.sipab.client.interfaces.QueryComments();
        try {
            mx.com.telcel.sipab.client.interfaces.QueryCommentsResponse _queryComments__return = port.queryComments(_queryComments_queryCommentsRequest);
            System.out.println("queryComments.result=" + _queryComments__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking notifyOrderExecutionTime...");
        mx.com.telcel.sipab.client.interfaces.NotifyOrderExecutionTime _notifyOrderExecutionTime_notifyOrderExecutionTimeRequest = new mx.com.telcel.sipab.client.interfaces.NotifyOrderExecutionTime();
        try {
            mx.com.telcel.sipab.client.interfaces.NotifyOrderExecutionTimeResponse _notifyOrderExecutionTime__return = port.notifyOrderExecutionTime(_notifyOrderExecutionTime_notifyOrderExecutionTimeRequest);
            System.out.println("notifyOrderExecutionTime.result=" + _notifyOrderExecutionTime__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking queryCustOfferingInst...");
        mx.com.telcel.sipab.client.interfaces.QueryCustOfferingInst _queryCustOfferingInst_queryCustOfferingInstRequest = new mx.com.telcel.sipab.client.interfaces.QueryCustOfferingInst();
        try {
            mx.com.telcel.sipab.client.interfaces.QueryCustOfferingInstResponse _queryCustOfferingInst__return = port.queryCustOfferingInst(_queryCustOfferingInst_queryCustOfferingInstRequest);
            System.out.println("queryCustOfferingInst.result=" + _queryCustOfferingInst__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking stockInICCID...");
        mx.com.telcel.sipab.client.interfaces.StockInICCID _stockInICCID_stockInICCIDRequest = new mx.com.telcel.sipab.client.interfaces.StockInICCID();
        try {
            mx.com.telcel.sipab.client.interfaces.StockInICCIDResponse _stockInICCID__return = port.stockInICCID(_stockInICCID_stockInICCIDRequest);
            System.out.println("stockInICCID.result=" + _stockInICCID__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking queryInvResourceInfo...");
        mx.com.telcel.sipab.client.interfaces.QueryInvResourceInfo _queryInvResourceInfo_queryInvResourceInfoRequest = new mx.com.telcel.sipab.client.interfaces.QueryInvResourceInfo();
        try {
            mx.com.telcel.sipab.client.interfaces.QueryInvResourceInfoResponse _queryInvResourceInfo__return = port.queryInvResourceInfo(_queryInvResourceInfo_queryInvResourceInfoRequest);
            System.out.println("queryInvResourceInfo.result=" + _queryInvResourceInfo__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking queryUnpaidInvoiceItem...");
        mx.com.telcel.sipab.client.interfaces.QueryUnpaidInvoiceItem _queryUnpaidInvoiceItem_queryUnpaidInvoiceItemRequest = new mx.com.telcel.sipab.client.interfaces.QueryUnpaidInvoiceItem();
        try {
            mx.com.telcel.sipab.client.interfaces.QueryUnpaidInvoiceItemResponse _queryUnpaidInvoiceItem__return = port.queryUnpaidInvoiceItem(_queryUnpaidInvoiceItem_queryUnpaidInvoiceItemRequest);
            System.out.println("queryUnpaidInvoiceItem.result=" + _queryUnpaidInvoiceItem__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking manageResourceRelation...");
        mx.com.telcel.sipab.client.interfaces.ManageResourceRelation _manageResourceRelation_manageResourceRelationRequest = new mx.com.telcel.sipab.client.interfaces.ManageResourceRelation();
        try {
            mx.com.telcel.sipab.client.interfaces.ManageResourceRelationResponse _manageResourceRelation__return = port.manageResourceRelation(_manageResourceRelation_manageResourceRelationRequest);
            System.out.println("manageResourceRelation.result=" + _manageResourceRelation__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking earlyPay...");
        mx.com.telcel.sipab.client.interfaces.EarlyPay _earlyPay_earlyPayRequest = new mx.com.telcel.sipab.client.interfaces.EarlyPay();
        try {
            mx.com.telcel.sipab.client.interfaces.EarlyPayResponse _earlyPay__return = port.earlyPay(_earlyPay_earlyPayRequest);
            System.out.println("earlyPay.result=" + _earlyPay__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking updateNumberUnlockTime...");
        mx.com.telcel.sipab.client.interfaces.UpdateNumberUnlockTime _updateNumberUnlockTime_updateNumberUnlockTimeRequest = new mx.com.telcel.sipab.client.interfaces.UpdateNumberUnlockTime();
        try {
            mx.com.telcel.sipab.client.interfaces.UpdateNumberUnlockTimeResponse _updateNumberUnlockTime__return = port.updateNumberUnlockTime(_updateNumberUnlockTime_updateNumberUnlockTimeRequest);
            System.out.println("updateNumberUnlockTime.result=" + _updateNumberUnlockTime__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking createComments...");
        mx.com.telcel.sipab.client.interfaces.CreateComments _createComments_createCommentsRequest = new mx.com.telcel.sipab.client.interfaces.CreateComments();
        try {
            mx.com.telcel.sipab.client.interfaces.CreateCommentsResponse _createComments__return = port.createComments(_createComments_createCommentsRequest);
            System.out.println("createComments.result=" + _createComments__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking queryEmployees...");
        mx.com.telcel.sipab.client.interfaces.QueryEmployees _queryEmployees_queryEmployeesRequest = new mx.com.telcel.sipab.client.interfaces.QueryEmployees();
        try {
            mx.com.telcel.sipab.client.interfaces.QueryEmployeesResponse _queryEmployees__return = port.queryEmployees(_queryEmployees_queryEmployeesRequest);
            System.out.println("queryEmployees.result=" + _queryEmployees__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking creditCheckCallBack...");
        mx.com.telcel.sipab.client.interfaces.CreditCheckCallBack _creditCheckCallBack_creditCheckCallBackRequest = new mx.com.telcel.sipab.client.interfaces.CreditCheckCallBack();
        try {
            mx.com.telcel.sipab.client.interfaces.CreditCheckCallBackResponse _creditCheckCallBack__return = port.creditCheckCallBack(_creditCheckCallBack_creditCheckCallBackRequest);
            System.out.println("creditCheckCallBack.result=" + _creditCheckCallBack__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getSubsOfferingInsts...");
        mx.com.telcel.sipab.client.interfaces.GetSubsOfferingInsts _getSubsOfferingInsts_getSubsOfferingInstsRequest = new mx.com.telcel.sipab.client.interfaces.GetSubsOfferingInsts();
        try {
            mx.com.telcel.sipab.client.interfaces.GetSubsOfferingInstsResponse _getSubsOfferingInsts__return = port.getSubsOfferingInsts(_getSubsOfferingInsts_getSubsOfferingInstsRequest);
            System.out.println("getSubsOfferingInsts.result=" + _getSubsOfferingInsts__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking querySubscriberByPage...");
        mx.com.telcel.sipab.client.interfaces.QuerySubscriberByPage _querySubscriberByPage_querySubscriberByPageRequest = new mx.com.telcel.sipab.client.interfaces.QuerySubscriberByPage();
        try {
            mx.com.telcel.sipab.client.interfaces.QuerySubscriberByPageResponse _querySubscriberByPage__return = port.querySubscriberByPage(_querySubscriberByPage_querySubscriberByPageRequest);
            System.out.println("querySubscriberByPage.result=" + _querySubscriberByPage__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getCustomerView...");
        mx.com.telcel.sipab.client.interfaces.GetCustomerView _getCustomerView_getCustomerViewRequest = new mx.com.telcel.sipab.client.interfaces.GetCustomerView();
        try {
            mx.com.telcel.sipab.client.interfaces.GetCustomerViewResponse _getCustomerView__return = port.getCustomerView(_getCustomerView_getCustomerViewRequest);
            System.out.println("getCustomerView.result=" + _getCustomerView__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }

        System.exit(0);
    }

}
