package mx.com.telcel.sipab.client.interfaces;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-10-24T12:33:26.350-06:00
 * Generated source version: 4.0.3
 *
 */
@WebService(targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", name = "TelcelInterfaceServices")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TelcelInterfaceServices {

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/notifyFinalDeliveryStatus")
    @WebResult(name = "notifyFinalDeliveryStatusResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "notifyFinalDeliveryStatusResponse")
    public NotifyFinalDeliveryStatusResponse notifyFinalDeliveryStatus(

        @WebParam(partName = "notifyFinalDeliveryStatusRequest", name = "notifyFinalDeliveryStatus", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        NotifyFinalDeliveryStatus notifyFinalDeliveryStatusRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/stockIn")
    @WebResult(name = "stockInResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "stockInResponse")
    public StockInResponse stockIn(

        @WebParam(partName = "stockInRequest", name = "stockIn", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        StockIn stockInRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/recibirResultado")
    @WebResult(name = "recibirResultadoResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "recibirResultadoResponse")
    public RecibirResultadoResponse recibirResultado(

        @WebParam(partName = "recibirResultadoRequest", name = "recibirResultado", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        RecibirResultado recibirResultadoRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/getCustByRFC4CreditCheck")
    @WebResult(name = "getCustByRFC4CreditCheckResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "getCustByRFC4CreditCheckResponse")
    public GetCustByRFC4CreditCheckResponse getCustByRFC4CreditCheck(

        @WebParam(partName = "getCustByRFC4CreditCheckRequest", name = "getCustByRFC4CreditCheck", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        GetCustByRFC4CreditCheck getCustByRFC4CreditCheckRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/telcelinterfaceservices/specialChangeOffering")
    @WebResult(name = "specialChangeOfferingResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "specialChangeOfferingResponse")
    public SpecialChangeOfferingResponse specialChangeOffering(

        @WebParam(partName = "specialChangeOfferingRequest", name = "specialChangeOffering", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        SpecialChangeOffering specialChangeOfferingRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/telcelinterfaceservices/queryDictItems")
    @WebResult(name = "queryDictItemsResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "queryDictItemsResponse")
    public QueryDictItemsResponse queryDictItems(

        @WebParam(partName = "queryDictItemsRequest", name = "queryDictItems", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        QueryDictItems queryDictItemsRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/changeSubsPayMode")
    @WebResult(name = "changeSubsPayModeResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "changeSubsPayModeResponse")
    public ChangeSubsPayModeResponse changeSubsPayMode(

        @WebParam(partName = "changeSubsPayModeRequest", name = "changeSubsPayMode", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        ChangeSubsPayMode changeSubsPayModeRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/getProfileSVA")
    @WebResult(name = "getProfileSVAResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "getProfileSVAResponse")
    public GetProfileSVAResponse getProfileSVA(

        @WebParam(partName = "getProfileSVARequest", name = "getProfileSVA", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        GetProfileSVA getProfileSVARequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/telcelinterfaceservices/queryFnF")
    @WebResult(name = "queryFnFResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "queryFnFResponse")
    public QueryFnFResponse queryFnF(

        @WebParam(partName = "queryFnFRequest", name = "queryFnF", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        QueryFnF queryFnFRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/telcelinterfaceservices/activateOfferingBySubscriber")
    @WebResult(name = "activateOfferingBySubscriberResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "activateOfferingBySubscriberResponse")
    public ActivateOfferingBySubscriberResponse activateOfferingBySubscriber(

        @WebParam(partName = "activateOfferingBySubscriberRequest", name = "activateOfferingBySubscriber", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        ActivateOfferingBySubscriber activateOfferingBySubscriberRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/telcelinterfaceservices/generateDeposit")
    @WebResult(name = "generateDepositResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "generateDepositResponse")
    public GenerateDepositResponse generateDeposit(

        @WebParam(partName = "generateDepositRequest", name = "generateDeposit", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        GenerateDeposit generateDepositRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/telcelinterfaceservices/querySysParam")
    @WebResult(name = "querySysParamResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "querySysParamResponse")
    public QuerySysParamResponse querySysParam(

        @WebParam(partName = "querySysParamRequest", name = "querySysParam", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        QuerySysParam querySysParamRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/telcelinterfaceservices/modifyCustInfoForDOL")
    @WebResult(name = "modifyCustInfoForDOLResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "modifyCustInfoForDOLResponse")
    public ModifyCustInfoForDOLResponse modifyCustInfoForDOL(

        @WebParam(partName = "modifyCustInfoForDOLRequest", name = "modifyCustInfoForDOL", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        ModifyCustInfoForDOL modifyCustInfoForDOLRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/changePriOfferingNew")
    @WebResult(name = "changePriOfferingNewResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "changePriOfferingNewResponse")
    public ChangePriOfferingNewResponse changePriOfferingNew(

        @WebParam(partName = "changePriOfferingNewRequest", name = "changePriOfferingNew", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        ChangePriOfferingNew changePriOfferingNewRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/getProductSVA")
    @WebResult(name = "getProductSVAResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "getProductSVAResponse")
    public GetProductSVAResponse getProductSVA(

        @WebParam(partName = "getProductSVARequest", name = "getProductSVA", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        GetProductSVA getProductSVARequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/telcelinterfaceservices/validateToken")
    @WebResult(name = "validateTokenResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "validateTokenResponse")
    public ValidateTokenResponse validateToken(

        @WebParam(partName = "validateTokenRequest", name = "validateToken", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        ValidateToken validateTokenRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/queryCustResourceDealType")
    @WebResult(name = "queryCustResourceDealTypeResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "queryCustResourceDealTypeResponse")
    public QueryCustResourceDealTypeResponse queryCustResourceDealType(

        @WebParam(partName = "queryCustResourceDealTypeRequest", name = "queryCustResourceDealType", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        QueryCustResourceDealType queryCustResourceDealTypeRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/queryAvailableBillCycles")
    @WebResult(name = "queryAvailableBillCyclesResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "queryAvailableBillCyclesResponse")
    public QueryAvailableBillCyclesResponse queryAvailableBillCycles(

        @WebParam(partName = "queryAvailableBillCyclesRequest", name = "queryAvailableBillCycles", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        QueryAvailableBillCycles queryAvailableBillCyclesRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/supplementIndividualCust")
    @WebResult(name = "supplementIndividualCustResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "supplementIndividualCustResponse")
    public SupplementIndividualCustResponse supplementIndividualCust(

        @WebParam(partName = "supplementIndividualCustRequest", name = "supplementIndividualCust", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        SupplementIndividualCust supplementIndividualCustRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/telcelinterfaceservices/lockOrUnlockIMEIService")
    @WebResult(name = "lockOrUnlockIMEIServiceResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "lockOrUnlockIMEIServiceResponse")
    public LockOrUnlockIMEIServiceResponse lockOrUnlockIMEIService(

        @WebParam(partName = "lockOrUnlockIMEIServiceRequest", name = "lockOrUnlockIMEIService", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        LockOrUnlockIMEIService lockOrUnlockIMEIServiceRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/telcelinterfaceservices/queryIMEI")
    @WebResult(name = "queryIMEIResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "queryIMEIResponse")
    public QueryIMEIResponse queryIMEI(

        @WebParam(partName = "queryIMEIRequest", name = "queryIMEI", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        QueryIMEI queryIMEIRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/queryIoTdevice")
    @WebResult(name = "queryIoTdeviceResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "queryIoTdeviceResponse")
    public QueryIoTdeviceResponse queryIoTdevice(

        @WebParam(partName = "queryIoTdeviceRequest", name = "queryIoTdevice", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        QueryIoTdevice queryIoTdeviceRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/updateInvResourceInfo")
    @WebResult(name = "updateInvResourceInfoResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "updateInvResourceInfoResponse")
    public UpdateInvResourceInfoResponse updateInvResourceInfo(

        @WebParam(partName = "updateInvResourceInfoRequest", name = "updateInvResourceInfo", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        UpdateInvResourceInfo updateInvResourceInfoRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/calcPenalty")
    @WebResult(name = "calcPenaltyResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "calcPenaltyResponse")
    public CalcPenaltyResponse calcPenalty(

        @WebParam(partName = "calcPenaltyRequest", name = "calcPenalty", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        CalcPenalty calcPenaltyRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/telcelinterfaceservices/createGroupCustomer")
    @WebResult(name = "createGroupCustomerResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "createGroupCustomerResponse")
    public CreateGroupCustomerResponse createGroupCustomer(

        @WebParam(partName = "createGroupCustomerRequest", name = "createGroupCustomer", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        CreateGroupCustomer createGroupCustomerRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/getSubsCustAcctBasicInfo")
    @WebResult(name = "getSubsCustAcctBasicInfoResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "getSubsCustAcctBasicInfoResponse")
    public GetSubsCustAcctBasicInfoResponse getSubsCustAcctBasicInfo(

        @WebParam(partName = "getSubsCustAcctBasicInfoRequest", name = "getSubsCustAcctBasicInfo", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        GetSubsCustAcctBasicInfo getSubsCustAcctBasicInfoRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/telcelinterfaceservices/sendIMEINote")
    @WebResult(name = "sendIMEINoteResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "sendIMEINoteResponse")
    public SendIMEINoteResponse sendIMEINote(

        @WebParam(partName = "sendIMEINoteRequest", name = "sendIMEINote", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        SendIMEINote sendIMEINoteRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/telcelinterfaceservices/queryAvailableAccounts")
    @WebResult(name = "queryAvailableAccountsResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "queryAvailableAccountsResponse")
    public QueryAvailableAccountsResponse queryAvailableAccounts(

        @WebParam(partName = "queryAvailableAccountsRequest", name = "queryAvailableAccounts", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        QueryAvailableAccounts queryAvailableAccountsRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/returnResource")
    @WebResult(name = "returnResourceResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "returnResourceResponse")
    public ReturnResourceResponse returnResource(

        @WebParam(partName = "returnResourceRequest", name = "returnResource", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        ReturnResource returnResourceRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/validateCPO2Platino")
    @WebResult(name = "validateCPO2PlatinoResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "validateCPO2PlatinoResponse")
    public ValidateCPO2PlatinoResponse validateCPO2Platino(

        @WebParam(partName = "validateCPO2PlatinoRequest", name = "validateCPO2Platino", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        ValidateCPO2Platino validateCPO2PlatinoRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/batchCreateNewSub")
    @WebResult(name = "batchCreateNewSubResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "batchCreateNewSubResponse")
    public BatchCreateNewSubResponse batchCreateNewSub(

        @WebParam(partName = "batchCreateNewSubRequest", name = "batchCreateNewSub", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        BatchCreateNewSub batchCreateNewSubRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/reserveBusiness")
    @WebResult(name = "reserveBusinessResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "reserveBusinessResponse")
    public ReserveBusinessResponse reserveBusiness(

        @WebParam(partName = "reserveBusinessRequest", name = "reserveBusiness", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        ReserveBusiness reserveBusinessRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/getOrderDetailInfo")
    @WebResult(name = "getOrderDetailInfoResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "getOrderDetailInfoResponse")
    public GetOrderDetailInfoResponse getOrderDetailInfo(

        @WebParam(partName = "getOrderDetailInfoRequest", name = "getOrderDetailInfo", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        GetOrderDetailInfo getOrderDetailInfoRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/queryInsuranceOffer")
    @WebResult(name = "queryInsuranceOfferResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "queryInsuranceOfferResponse")
    public QueryInsuranceOfferResponse queryInsuranceOffer(

        @WebParam(partName = "queryInsuranceOfferRequest", name = "queryInsuranceOffer", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        QueryInsuranceOffer queryInsuranceOfferRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/changeRegion")
    @WebResult(name = "changeRegionResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "changeRegionResponse")
    public ChangeRegionResponse changeRegion(

        @WebParam(partName = "changeRegionRequest", name = "changeRegion", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        ChangeRegion changeRegionRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/telcelinterfaceservices/crmRechargeRollBack")
    @WebResult(name = "crmRechargeRollBackResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "crmRechargeRollBackResponse")
    public CrmRechargeRollBackResponse crmRechargeRollBack(

        @WebParam(partName = "crmRechargeRollBackRequest", name = "crmRechargeRollBack", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        CrmRechargeRollBack crmRechargeRollBackRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/getBatchFile")
    @WebResult(name = "getBatchFileResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "getBatchFileResponse")
    public GetBatchFileResponse getBatchFile(

        @WebParam(partName = "getBatchFileRequest", name = "getBatchFile", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        GetBatchFile getBatchFileRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/telcelinterfaceservices/getOrders")
    @WebResult(name = "getOrdersResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "getOrdersResponse")
    public GetOrdersResponse getOrders(

        @WebParam(partName = "getOrdersRequest", name = "getOrders", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        GetOrders getOrdersRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/validateCard")
    @WebResult(name = "validateCardResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "validateCardResponse")
    public ValidateCardResponse validateCard(

        @WebParam(partName = "validateCardRequest", name = "validateCard", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        ValidateCard validateCardRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/previewEarlyPay")
    @WebResult(name = "previewEarlyPayResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "previewEarlyPayResponse")
    public PreviewEarlyPayResponse previewEarlyPay(

        @WebParam(partName = "previewEarlyPayRequest", name = "previewEarlyPay", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        PreviewEarlyPay previewEarlyPayRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/actualizarHandsetStatus")
    @WebResult(name = "actualizarHandsetStatusResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "actualizarHandsetStatusResponse")
    public ActualizarHandsetStatusResponse actualizarHandsetStatus(

        @WebParam(partName = "actualizarHandsetStatusRequest", name = "actualizarHandsetStatus", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        ActualizarHandsetStatus actualizarHandsetStatusRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/telcelinterfaceservices/swapResource")
    @WebResult(name = "swapResourceResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "swapResourceResponse")
    public SwapResourceResponse swapResource(

        @WebParam(partName = "swapResourceRequest", name = "swapResource", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        SwapResource swapResourceRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/telcelinterfaceservices/manageFnF")
    @WebResult(name = "manageFnFResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "manageFnFResponse")
    public ManageFnFResponse manageFnF(

        @WebParam(partName = "manageFnFRequest", name = "manageFnF", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        ManageFnF manageFnFRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/telcelinterfaceservices/queryEntityRelations")
    @WebResult(name = "queryEntityRelationsResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "queryEntityRelationsResponse")
    public QueryEntityRelationsResponse queryEntityRelations(

        @WebParam(partName = "queryEntityRelationsRequest", name = "queryEntityRelations", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        QueryEntityRelations queryEntityRelationsRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/querySubsServiceContract")
    @WebResult(name = "querySubsServiceContractResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "querySubsServiceContractResponse")
    public QuerySubsServiceContractResponse querySubsServiceContract(

        @WebParam(partName = "querySubsServiceContractRequest", name = "querySubsServiceContract", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        QuerySubsServiceContract querySubsServiceContractRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/telcelinterfaceservices/padrinoZeekMiAutoRegistration")
    @WebResult(name = "padrinoZeekMiAutoRegistrationResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "padrinoZeekMiAutoRegistrationResponse")
    public PadrinoZeekMiAutoRegistrationResponse padrinoZeekMiAutoRegistration(

        @WebParam(partName = "padrinoZeekMiAutoRegistrationRequest", name = "padrinoZeekMiAutoRegistration", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        PadrinoZeekMiAutoRegistration padrinoZeekMiAutoRegistrationRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/queryComments")
    @WebResult(name = "queryCommentsResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "queryCommentsResponse")
    public QueryCommentsResponse queryComments(

        @WebParam(partName = "queryCommentsRequest", name = "queryComments", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        QueryComments queryCommentsRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/notifyOrderExecutionTime")
    @WebResult(name = "notifyOrderExecutionTimeResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "notifyOrderExecutionTimeResponse")
    public NotifyOrderExecutionTimeResponse notifyOrderExecutionTime(

        @WebParam(partName = "notifyOrderExecutionTimeRequest", name = "notifyOrderExecutionTime", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        NotifyOrderExecutionTime notifyOrderExecutionTimeRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/queryCustOfferingInst")
    @WebResult(name = "queryCustOfferingInstResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "queryCustOfferingInstResponse")
    public QueryCustOfferingInstResponse queryCustOfferingInst(

        @WebParam(partName = "queryCustOfferingInstRequest", name = "queryCustOfferingInst", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        QueryCustOfferingInst queryCustOfferingInstRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/stockInICCID")
    @WebResult(name = "stockInICCIDResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "stockInICCIDResponse")
    public StockInICCIDResponse stockInICCID(

        @WebParam(partName = "stockInICCIDRequest", name = "stockInICCID", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        StockInICCID stockInICCIDRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/queryInvResourceInfo")
    @WebResult(name = "queryInvResourceInfoResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "queryInvResourceInfoResponse")
    public QueryInvResourceInfoResponse queryInvResourceInfo(

        @WebParam(partName = "queryInvResourceInfoRequest", name = "queryInvResourceInfo", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        QueryInvResourceInfo queryInvResourceInfoRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/queryUnpaidInvoiceItem")
    @WebResult(name = "queryUnpaidInvoiceItemResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "queryUnpaidInvoiceItemResponse")
    public QueryUnpaidInvoiceItemResponse queryUnpaidInvoiceItem(

        @WebParam(partName = "queryUnpaidInvoiceItemRequest", name = "queryUnpaidInvoiceItem", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        QueryUnpaidInvoiceItem queryUnpaidInvoiceItemRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/manageResourceRelation")
    @WebResult(name = "manageResourceRelationResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "manageResourceRelationResponse")
    public ManageResourceRelationResponse manageResourceRelation(

        @WebParam(partName = "manageResourceRelationRequest", name = "manageResourceRelation", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        ManageResourceRelation manageResourceRelationRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/earlyPay")
    @WebResult(name = "earlyPayResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "earlyPayResponse")
    public EarlyPayResponse earlyPay(

        @WebParam(partName = "earlyPayRequest", name = "earlyPay", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        EarlyPay earlyPayRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/updateNumberUnlockTime")
    @WebResult(name = "updateNumberUnlockTimeResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "updateNumberUnlockTimeResponse")
    public UpdateNumberUnlockTimeResponse updateNumberUnlockTime(

        @WebParam(partName = "updateNumberUnlockTimeRequest", name = "updateNumberUnlockTime", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        UpdateNumberUnlockTime updateNumberUnlockTimeRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/createComments")
    @WebResult(name = "createCommentsResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "createCommentsResponse")
    public CreateCommentsResponse createComments(

        @WebParam(partName = "createCommentsRequest", name = "createComments", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        CreateComments createCommentsRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/queryEmployees")
    @WebResult(name = "queryEmployeesResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "queryEmployeesResponse")
    public QueryEmployeesResponse queryEmployees(

        @WebParam(partName = "queryEmployeesRequest", name = "queryEmployees", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        QueryEmployees queryEmployeesRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/creditCheckCallBack")
    @WebResult(name = "creditCheckCallBackResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "creditCheckCallBackResponse")
    public CreditCheckCallBackResponse creditCheckCallBack(

        @WebParam(partName = "creditCheckCallBackRequest", name = "creditCheckCallBack", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        CreditCheckCallBack creditCheckCallBackRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/telcelinterfaceservices/getSubsOfferingInsts")
    @WebResult(name = "getSubsOfferingInstsResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "getSubsOfferingInstsResponse")
    public GetSubsOfferingInstsResponse getSubsOfferingInsts(

        @WebParam(partName = "getSubsOfferingInstsRequest", name = "getSubsOfferingInsts", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        GetSubsOfferingInsts getSubsOfferingInstsRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/querySubscriberByPage")
    @WebResult(name = "querySubscriberByPageResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "querySubscriberByPageResponse")
    public QuerySubscriberByPageResponse querySubscriberByPage(

        @WebParam(partName = "querySubscriberByPageRequest", name = "querySubscriberByPage", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        QuerySubscriberByPage querySubscriberByPageRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices/getCustomerView")
    @WebResult(name = "getCustomerViewResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices", partName = "getCustomerViewResponse")
    public GetCustomerViewResponse getCustomerView(

        @WebParam(partName = "getCustomerViewRequest", name = "getCustomerView", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/telcelinterfaceservices")
        GetCustomerView getCustomerViewRequest
    ) throws GeneralException;
}
