package mx.com.telcel.sipab.client.crm;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-10-24T12:33:08.680-06:00
 * Generated source version: 4.0.3
 *
 */
@WebServiceClient(name = "CustomerManagementServiceHttpService",
                  wsdlLocation = "http://iib.telcel.com:1722/mexico/telcel/di/sds/bes/crm/customermanagementservice/v6?wsdl",
                  targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/customermanagementservice")
public class CustomerManagementServiceHttpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/customermanagementservice", "CustomerManagementServiceHttpService");
    public final static QName CustomerManagementServiceHttpPort = new QName("http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/customermanagementservice", "CustomerManagementServiceHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://iib.telcel.com:1722/mexico/telcel/di/sds/bes/crm/customermanagementservice/v6?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CustomerManagementServiceHttpService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://iib.telcel.com:1722/mexico/telcel/di/sds/bes/crm/customermanagementservice/v6?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CustomerManagementServiceHttpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerManagementServiceHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerManagementServiceHttpService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CustomerManagementServiceHttpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CustomerManagementServiceHttpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CustomerManagementServiceHttpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CustomerManagementService
     */
    @WebEndpoint(name = "CustomerManagementServiceHttpPort")
    public CustomerManagementService getCustomerManagementServiceHttpPort() {
        return super.getPort(CustomerManagementServiceHttpPort, CustomerManagementService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerManagementService
     */
    @WebEndpoint(name = "CustomerManagementServiceHttpPort")
    public CustomerManagementService getCustomerManagementServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(CustomerManagementServiceHttpPort, CustomerManagementService.class, features);
    }

}
