package mx.com.telcel.sipab.client.crm;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-10-24T12:33:08.659-06:00
 * Generated source version: 4.0.3
 *
 */
@WebService(targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/customermanagementservice", name = "CustomerManagementService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CustomerManagementService {

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/customermanagementservice/getSubscriberOfferingInst")
    @WebResult(name = "getSubscriberOfferingInstResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/customermanagementservice", partName = "getSubscriberOfferingInstResponse")
    public GetSubscriberOfferingInstResponse getSubscriberOfferingInst(

        @WebParam(partName = "getSubscriberOfferingInstRequest", name = "getSubscriberOfferingInst", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/customermanagementservice")
        GetSubscriberOfferingInst getSubscriberOfferingInstRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/customermanagementservice/getAccountInfo")
    @WebResult(name = "getAccountInfoResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/customermanagementservice", partName = "getAccountInfoResponse")
    public GetAccountInfoResponse getAccountInfo(

        @WebParam(partName = "getAccountInfoRequest", name = "getAccountInfo", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/customermanagementservice")
        GetAccountInfo getAccountInfoRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/customermanagementservice/getCustomerDetailInfo")
    @WebResult(name = "getCustomerDetailInfoResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/customermanagementservice", partName = "getCustomerDetailInfoResponse")
    public GetCustomerDetailInfoResponse getCustomerDetailInfo(

        @WebParam(partName = "getCustomerDetailInfoRequest", name = "getCustomerDetailInfo", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/customermanagementservice")
        GetCustomerDetailInfo getCustomerDetailInfoRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/customermanagementservice/getSubscriberInfo")
    @WebResult(name = "getSubscriberInfoResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/customermanagementservice", partName = "getSubscriberInfoResponse")
    public GetSubscriberInfoResponse getSubscriberInfo(

        @WebParam(partName = "getSubscriberInfoRequest", name = "getSubscriberInfo", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/customermanagementservice")
        GetSubscriberInfo getSubscriberInfoRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/customermanagementservice/getResourceInfo")
    @WebResult(name = "getResourceInfoResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/customermanagementservice", partName = "getResourceInfoResponse")
    public GetResourceInfoResponse getResourceInfo(

        @WebParam(partName = "getResourceInfoRequest", name = "getResourceInfo", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/customermanagementservice")
        GetResourceInfo getResourceInfoRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/customermanagementservice/getCustomerBasicInfo")
    @WebResult(name = "getCustomerBasicInfoResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/customermanagementservice", partName = "getCustomerBasicInfoResponse")
    public GetCustomerBasicInfoResponse getCustomerBasicInfo(

        @WebParam(partName = "getCustomerBasicInfoRequest", name = "getCustomerBasicInfo", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/customermanagementservice")
        GetCustomerBasicInfo getCustomerBasicInfoRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/customermanagementservice/getContractDetail")
    @WebResult(name = "getContractDetailResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/customermanagementservice", partName = "getContractDetailResponse")
    public GetContractDetailResponse getContractDetail(

        @WebParam(partName = "getContractDetailRequest", name = "getContractDetail", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/customermanagementservice")
        GetContractDetail getContractDetailRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/customermanagementservice/getNetworkService")
    @WebResult(name = "getNetworkServiceResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/customermanagementservice", partName = "getNetworkServiceResponse")
    public GetNetworkServiceResponse getNetworkService(

        @WebParam(partName = "getNetworkServiceRequest", name = "getNetworkService", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/customermanagementservice")
        GetNetworkService getNetworkServiceRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/customermanagementservice/getGroupSubscribers")
    @WebResult(name = "getGroupSubscribersResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/customermanagementservice", partName = "getGroupSubscribersResponse")
    public GetGroupSubscribersResponse getGroupSubscribers(

        @WebParam(partName = "getGroupSubscribersRequest", name = "getGroupSubscribers", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/customermanagementservice")
        GetGroupSubscribers getGroupSubscribersRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/customermanagementservice/getOfferingProp")
    @WebResult(name = "getOfferingPropResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/customermanagementservice", partName = "getOfferingPropResponse")
    public GetOfferingPropResponse getOfferingProp(

        @WebParam(partName = "getOfferingPropRequest", name = "getOfferingProp", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/crm/esb/customermanagementservice")
        GetOfferingProp getOfferingPropRequest
    ) throws GeneralException;
}
