package mx.com.telcel.sipab.client.ldapAut;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-10-24T12:32:50.140-06:00
 * Generated source version: 4.0.3
 *
 */
@WebServiceClient(name = "ldapService",
                  wsdlLocation = "http://serviciosidentidad.telcel.com:8000/ldapWebBroker/ldapService/LdapService.wsdl",
                  targetNamespace = "http://test.dswi.gsa.telcel.com/")
public class LdapService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://test.dswi.gsa.telcel.com/", "ldapService");
    public final static QName LdapPort = new QName("http://test.dswi.gsa.telcel.com/", "ldapPort");
    static {
        URL url = null;
        try {
            url = new URL("http://serviciosidentidad.telcel.com:8000/ldapWebBroker/ldapService/LdapService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LdapService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://serviciosidentidad.telcel.com:8000/ldapWebBroker/ldapService/LdapService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LdapService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LdapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LdapService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public LdapService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public LdapService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public LdapService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Ldap
     */
    @WebEndpoint(name = "ldapPort")
    public Ldap getLdapPort() {
        return super.getPort(LdapPort, Ldap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Ldap
     */
    @WebEndpoint(name = "ldapPort")
    public Ldap getLdapPort(WebServiceFeature... features) {
        return super.getPort(LdapPort, Ldap.class, features);
    }

}
