package mx.com.telcel.sipab.client.ldapAut;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-10-24T12:32:50.128-06:00
 * Generated source version: 4.0.3
 *
 */
@WebService(targetNamespace = "http://test.dswi.gsa.telcel.com/", name = "ldap")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Ldap {

    @WebMethod
    @Action(input = "http://test.dswi.gsa.telcel.com/ldap/autenticarUsuarioAppAESRequest", output = "http://test.dswi.gsa.telcel.com/ldap/autenticarUsuarioAppAESResponse")
    @WebResult(name = "autenticarUsuarioAppAESResponse", targetNamespace = "http://test.dswi.gsa.telcel.com/", partName = "parameters")
    public AutenticarUsuarioAppAESResponse autenticarUsuarioAppAES(

        @WebParam(partName = "parameters", name = "autenticarUsuarioAppAES", targetNamespace = "http://test.dswi.gsa.telcel.com/")
        AutenticarUsuarioAppAES parameters
    );

    @WebMethod
    @Action(input = "http://test.dswi.gsa.telcel.com/ldap/autenticarUsuarioAppRequest", output = "http://test.dswi.gsa.telcel.com/ldap/autenticarUsuarioAppResponse")
    @WebResult(name = "autenticarUsuarioAppResponse", targetNamespace = "http://test.dswi.gsa.telcel.com/", partName = "parameters")
    public AutenticarUsuarioAppResponse autenticarUsuarioApp(

        @WebParam(partName = "parameters", name = "autenticarUsuarioApp", targetNamespace = "http://test.dswi.gsa.telcel.com/")
        AutenticarUsuarioApp parameters
    );
}
