apiVersion: v1
kind: ConfigMap
metadata:
  name: sipab-config
  labels:
    app: sipab-webservice
data:
  application.properties: |
    spring.application.name=SIPABWebService
    server.port=8181
    
    # Logging
    logging.level.root=INFO
    logging.level.mx.com.telcel.sipab=DEBUG
    
    # Actuator para health checks
    management.endpoints.web.exposure.include=health,info,metrics
    management.endpoint.health.probes.enabled=true
    management.endpoint.health.liveness-state.enabled=true
    management.endpoint.health.readiness-state.enabled=true
    
    # Configuración de integración con servicios externos
    integration.service.date-time.format=yyyy-MM-dd'T'HH:mm:ss.SSSXXX
    
    # CBS Configuration
    integration.service.cbs.headers.Bes-usuario=102
    integration.service.cbs.send-by=openshift-deployment
    
    # CRM Configuration
    integration.service.crm.headers.Client-Id=${CRM_CLIENT_ID}
    integration.service.crm.send-by=openshift-deployment
    
    # Interfaces Configuration
    integration.service.interfaces.headers.Client-Id=${INTERFACES_CLIENT_ID}
    integration.service.interfaces.send-by=openshift-deployment
    
    # ColdView Configuration
    integration.service.coldView.usuario=${COLDVIEW_USUARIO}
    integration.service.coldView.sistema=M
    integration.service.coldView.resourceConfig=cv_mobile

