apiVersion: v1
kind: Secret
metadata:
  name: oracle-db-secret
  labels:
    app: sipab-webservice
type: Opaque
data:
  # IMPORTANTE: Estos valores deben estar en base64
  # Para codificar: echo -n "valor" | base64
  # Ejemplo para URL: echo -n "jdbc:oracle:thin:@10.191.105.18:1550/mbgwdes" | base64
  url: <BASE64_ENCODED_URL>
  username: <BASE64_ENCODED_USERNAME>
  password: <BASE64_ENCODED_PASSWORD>

---
apiVersion: v1
kind: Secret
metadata:
  name: sipab-crm-secret
  labels:
    app: sipab-webservice
type: Opaque
data:
  client-id: <BASE64_ENCODED_CRM_CLIENT_ID>
  token: <BASE64_ENCODED_CRM_TOKEN>

---
apiVersion: v1
kind: Secret
metadata:
  name: sipab-coldview-secret
  labels:
    app: sipab-webservice
type: Opaque
data:
  usuario: <BASE64_ENCODED_COLDVIEW_USUARIO>
  contrasenia: <BASE64_ENCODED_COLDVIEW_PASSWORD>

