
package mx.com.telcel.sipab.client.tt;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-10-24T12:33:30.239-06:00
 * Generated source version: 4.0.3
 *
 */
public final class TroubleTicketService_TroubleTicketServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.amx.com.mx/mexico/telcel/di/sds/bes/tt/esb/troubleticketservice", "TroubleTicketServiceHttpService");

    private TroubleTicketService_TroubleTicketServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TroubleTicketServiceHttpService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        TroubleTicketServiceHttpService ss = new TroubleTicketServiceHttpService(wsdlURL, SERVICE_NAME);
        TroubleTicketService port = ss.getTroubleTicketServiceHttpPort();

        {
        System.out.println("Invoking queryTTList...");
        mx.com.telcel.sipab.client.tt.QueryTTList _queryTTList_queryTTListRequest = new mx.com.telcel.sipab.client.tt.QueryTTList();
        try {
            mx.com.telcel.sipab.client.tt.QueryTTListResponse _queryTTList__return = port.queryTTList(_queryTTList_queryTTListRequest);
            System.out.println("queryTTList.result=" + _queryTTList__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking queryMonitoringTT...");
        mx.com.telcel.sipab.client.tt.QueryMonitoringTT _queryMonitoringTT_queryMonitoringTTRequest = new mx.com.telcel.sipab.client.tt.QueryMonitoringTT();
        try {
            mx.com.telcel.sipab.client.tt.QueryMonitoringTTResponse _queryMonitoringTT__return = port.queryMonitoringTT(_queryMonitoringTT_queryMonitoringTTRequest);
            System.out.println("queryMonitoringTT.result=" + _queryMonitoringTT__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking queryTTDetail...");
        mx.com.telcel.sipab.client.tt.QueryTTDetail _queryTTDetail_queryTTDetailRequest = new mx.com.telcel.sipab.client.tt.QueryTTDetail();
        try {
            mx.com.telcel.sipab.client.tt.QueryTTDetailResponse _queryTTDetail__return = port.queryTTDetail(_queryTTDetail_queryTTDetailRequest);
            System.out.println("queryTTDetail.result=" + _queryTTDetail__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking createTT...");
        mx.com.telcel.sipab.client.tt.CreateTT _createTT_createTTRequest = new mx.com.telcel.sipab.client.tt.CreateTT();
        try {
            mx.com.telcel.sipab.client.tt.CreateTTResponse _createTT__return = port.createTT(_createTT_createTTRequest);
            System.out.println("createTT.result=" + _createTT__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking updateTT...");
        mx.com.telcel.sipab.client.tt.UpdateTT _updateTT_updateTTRequest = new mx.com.telcel.sipab.client.tt.UpdateTT();
        try {
            mx.com.telcel.sipab.client.tt.UpdateTTResponse _updateTT__return = port.updateTT(_updateTT_updateTTRequest);
            System.out.println("updateTT.result=" + _updateTT__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking queryTTOperations...");
        mx.com.telcel.sipab.client.tt.QueryTTOperations _queryTTOperations_queryTTOperationsRequest = new mx.com.telcel.sipab.client.tt.QueryTTOperations();
        try {
            mx.com.telcel.sipab.client.tt.QueryTTOperationsResponse _queryTTOperations__return = port.queryTTOperations(_queryTTOperations_queryTTOperationsRequest);
            System.out.println("queryTTOperations.result=" + _queryTTOperations__return);

        } catch (GeneralException e) {
            System.out.println("Expected exception: generalException has occurred.");
            System.out.println(e.toString());
        }

            }

        System.exit(0);
    }

}
