package mx.com.telcel.sipab.client.tt;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-10-24T12:33:30.315-06:00
 * Generated source version: 4.0.3
 *
 */
@WebService(targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/tt/esb/troubleticketservice", name = "TroubleTicketService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TroubleTicketService {

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/tt/esb/troubleticketservice/queryTTList")
    @WebResult(name = "queryTTListResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/tt/esb/troubleticketservice", partName = "queryTTListResponse")
    public QueryTTListResponse queryTTList(

        @WebParam(partName = "queryTTListRequest", name = "queryTTList", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/tt/esb/troubleticketservice")
        QueryTTList queryTTListRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/tt/esb/troubleticketservice/queryMonitoringTT")
    @WebResult(name = "queryMonitoringTTResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/tt/esb/troubleticketservice", partName = "queryMonitoringTTResponse")
    public QueryMonitoringTTResponse queryMonitoringTT(

        @WebParam(partName = "queryMonitoringTTRequest", name = "queryMonitoringTT", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/tt/esb/troubleticketservice")
        QueryMonitoringTT queryMonitoringTTRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/tt/esb/troubleticketservice/queryTTDetail")
    @WebResult(name = "queryTTDetailResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/tt/esb/troubleticketservice", partName = "queryTTDetailResponse")
    public QueryTTDetailResponse queryTTDetail(

        @WebParam(partName = "queryTTDetailRequest", name = "queryTTDetail", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/tt/esb/troubleticketservice")
        QueryTTDetail queryTTDetailRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/tt/esb/troubleticketservice/createTT")
    @WebResult(name = "createTTResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/tt/esb/troubleticketservice", partName = "createTTResponse")
    public CreateTTResponse createTT(

        @WebParam(partName = "createTTRequest", name = "createTT", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/tt/esb/troubleticketservice")
        CreateTT createTTRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/tt/esb/troubleticketservice/updateTT")
    @WebResult(name = "updateTTResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/tt/esb/troubleticketservice", partName = "updateTTResponse")
    public UpdateTTResponse updateTT(

        @WebParam(partName = "updateTTRequest", name = "updateTT", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/tt/esb/troubleticketservice")
        UpdateTT updateTTRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/tt/esb/troubleticketservice/queryTTOperations")
    @WebResult(name = "queryTTOperationsResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/tt/esb/troubleticketservice", partName = "queryTTOperationsResponse")
    public QueryTTOperationsResponse queryTTOperations(

        @WebParam(partName = "queryTTOperationsRequest", name = "queryTTOperations", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/tt/esb/troubleticketservice")
        QueryTTOperations queryTTOperationsRequest
    ) throws GeneralException;
}
