package mx.com.telcel.sipab.client.tt;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-10-24T12:33:30.334-06:00
 * Generated source version: 4.0.3
 *
 */
@WebServiceClient(name = "TroubleTicketServiceHttpService",
                  wsdlLocation = "http://10.191.133.210:1722/mexico/telcel/di/sds/bes/tt/troubleticketservice/v1?WSDL",
                  targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/tt/esb/troubleticketservice")
public class TroubleTicketServiceHttpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.amx.com.mx/mexico/telcel/di/sds/bes/tt/esb/troubleticketservice", "TroubleTicketServiceHttpService");
    public final static QName TroubleTicketServiceHttpPort = new QName("http://www.amx.com.mx/mexico/telcel/di/sds/bes/tt/esb/troubleticketservice", "TroubleTicketServiceHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.191.133.210:1722/mexico/telcel/di/sds/bes/tt/troubleticketservice/v1?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TroubleTicketServiceHttpService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://10.191.133.210:1722/mexico/telcel/di/sds/bes/tt/troubleticketservice/v1?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public TroubleTicketServiceHttpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TroubleTicketServiceHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TroubleTicketServiceHttpService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TroubleTicketServiceHttpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TroubleTicketServiceHttpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TroubleTicketServiceHttpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns TroubleTicketService
     */
    @WebEndpoint(name = "TroubleTicketServiceHttpPort")
    public TroubleTicketService getTroubleTicketServiceHttpPort() {
        return super.getPort(TroubleTicketServiceHttpPort, TroubleTicketService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TroubleTicketService
     */
    @WebEndpoint(name = "TroubleTicketServiceHttpPort")
    public TroubleTicketService getTroubleTicketServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(TroubleTicketServiceHttpPort, TroubleTicketService.class, features);
    }

}
