package mx.com.telcel.sipab.client.ldap;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-10-24T12:32:49.213-06:00
 * Generated source version: 4.0.3
 *
 */
@WebService(targetNamespace = "http://negocio.ldap.dswi.gcr.telcel.com", name = "SearchLdap")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SearchLdap {

    @WebMethod(action = "buscaEmpleado")
    @WebResult(name = "buscaEmpleadoResponse", targetNamespace = "http://negocio.ldap.dswi.gcr.telcel.com", partName = "parameters")
    public BuscaEmpleadoResponse buscaEmpleado(

        @WebParam(partName = "parameters", name = "buscaEmpleado", targetNamespace = "http://negocio.ldap.dswi.gcr.telcel.com")
        BuscaEmpleado parameters
    );

    @WebMethod(action = "buscaJefeInmediato")
    @WebResult(name = "buscaJefeInmediatoResponse", targetNamespace = "http://negocio.ldap.dswi.gcr.telcel.com", partName = "parameters")
    public BuscaJefeInmediatoResponse buscaJefeInmediato(

        @WebParam(partName = "parameters", name = "buscaJefeInmediato", targetNamespace = "http://negocio.ldap.dswi.gcr.telcel.com")
        BuscaJefeInmediato parameters
    );

    @WebMethod(action = "buscaSubdirector")
    @WebResult(name = "buscaSubdirectorResponse", targetNamespace = "http://negocio.ldap.dswi.gcr.telcel.com", partName = "parameters")
    public BuscaSubdirectorResponse buscaSubdirector(

        @WebParam(partName = "parameters", name = "buscaSubdirector", targetNamespace = "http://negocio.ldap.dswi.gcr.telcel.com")
        BuscaSubdirector parameters
    );

    @WebMethod(action = "buscaDirector")
    @WebResult(name = "buscaDirectorResponse", targetNamespace = "http://negocio.ldap.dswi.gcr.telcel.com", partName = "parameters")
    public BuscaDirectorResponse buscaDirector(

        @WebParam(partName = "parameters", name = "buscaDirector", targetNamespace = "http://negocio.ldap.dswi.gcr.telcel.com")
        BuscaDirector parameters
    );

    @WebMethod(action = "buscaGerente")
    @WebResult(name = "buscaGerenteResponse", targetNamespace = "http://negocio.ldap.dswi.gcr.telcel.com", partName = "parameters")
    public BuscaGerenteResponse buscaGerente(

        @WebParam(partName = "parameters", name = "buscaGerente", targetNamespace = "http://negocio.ldap.dswi.gcr.telcel.com")
        BuscaGerente parameters
    );

    @WebMethod(action = "buscaEmpleadoPerfilCallidus")
    @WebResult(name = "buscaEmpleadoPerfilCallidusResponse", targetNamespace = "http://negocio.ldap.dswi.gcr.telcel.com", partName = "parameters")
    public BuscaEmpleadoPerfilCallidusResponse buscaEmpleadoPerfilCallidus(

        @WebParam(partName = "parameters", name = "buscaEmpleadoPerfilCallidus", targetNamespace = "http://negocio.ldap.dswi.gcr.telcel.com")
        BuscaEmpleadoPerfilCallidus parameters
    );
}
