package mx.com.telcel.sipab.client.ldap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-10-24T12:32:49.234-06:00
 * Generated source version: 4.0.3
 *
 */
@WebServiceClient(name = "SearchLdapService",
                  wsdlLocation = "http://serviciosidentidad.telcel.com:8000/DswiSearchLdap/services/SearchLdap/wsdl/SearchLdap.wsdl",
                  targetNamespace = "http://negocio.ldap.dswi.gcr.telcel.com")
public class SearchLdapService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://negocio.ldap.dswi.gcr.telcel.com", "SearchLdapService");
    public final static QName SearchLdap = new QName("http://negocio.ldap.dswi.gcr.telcel.com", "SearchLdap");
    static {
        URL url = null;
        try {
            url = new URL("http://serviciosidentidad.telcel.com:8000/DswiSearchLdap/services/SearchLdap/wsdl/SearchLdap.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SearchLdapService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://serviciosidentidad.telcel.com:8000/DswiSearchLdap/services/SearchLdap/wsdl/SearchLdap.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SearchLdapService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SearchLdapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SearchLdapService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SearchLdapService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SearchLdapService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SearchLdapService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SearchLdap
     */
    @WebEndpoint(name = "SearchLdap")
    public SearchLdap getSearchLdap() {
        return super.getPort(SearchLdap, SearchLdap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SearchLdap
     */
    @WebEndpoint(name = "SearchLdap")
    public SearchLdap getSearchLdap(WebServiceFeature... features) {
        return super.getPort(SearchLdap, SearchLdap.class, features);
    }

}
