package mx.com.telcel.sipab.client.cbs;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-10-24T12:33:03.546-06:00
 * Generated source version: 4.0.3
 *
 */
@WebService(targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", name = "ArServices")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ArServices {

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/paymentRollBack")
    @WebResult(name = "paymentRollBackResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", partName = "paymentRollBackResponse")
    public PaymentRollBackResponse paymentRollBack(

        @WebParam(partName = "paymentRollBackRequest", name = "paymentRollBack", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices")
        PaymentRollBack paymentRollBackRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/refund")
    @WebResult(name = "refundResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", partName = "refundResponse")
    public RefundResponse refund(

        @WebParam(partName = "refundRequest", name = "refund", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices")
        Refund refundRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/queryTransferLog")
    @WebResult(name = "queryTransferLogResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", partName = "queryTransferLogResponse")
    public QueryTransferLogResponse queryTransferLog(

        @WebParam(partName = "queryTransferLogRequest", name = "queryTransferLog", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices")
        QueryTransferLog queryTransferLogRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/queryInvoice")
    @WebResult(name = "queryInvoiceResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", partName = "queryInvoiceResponse")
    public QueryInvoiceResponse queryInvoice(

        @WebParam(partName = "queryInvoiceRequest", name = "queryInvoice", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices")
        QueryInvoice queryInvoiceRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/payment")
    @WebResult(name = "paymentResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", partName = "paymentResponse")
    public PaymentResponse payment(

        @WebParam(partName = "paymentRequest", name = "payment", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices")
        Payment paymentRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/adjustment")
    @WebResult(name = "adjustmentResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", partName = "adjustmentResponse")
    public AdjustmentResponse adjustment(

        @WebParam(partName = "adjustmentRequest", name = "adjustment", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices")
        Adjustment adjustmentRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/recharge")
    @WebResult(name = "rechargeResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", partName = "rechargeResponse")
    public RechargeResponse recharge(

        @WebParam(partName = "rechargeRequest", name = "recharge", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices")
        Recharge rechargeRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/arservices/subAccountLoan")
    @WebResult(name = "subAccountLoanResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", partName = "subAccountLoanResponse")
    public SubAccountLoanResponse subAccountLoan(

        @WebParam(partName = "subAccountLoanRequest", name = "subAccountLoan", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices")
        SubAccountLoan subAccountLoanRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/queryPaymentLog")
    @WebResult(name = "queryPaymentLogResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", partName = "queryPaymentLogResponse")
    public QueryPaymentLogResponse queryPaymentLog(

        @WebParam(partName = "queryPaymentLogRequest", name = "queryPaymentLog", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices")
        QueryPaymentLog queryPaymentLogRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/querySumBalanceAndCredit")
    @WebResult(name = "querySumBalanceAndCreditResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", partName = "querySumBalanceAndCreditResponse")
    public QuerySumBalanceAndCreditResponse querySumBalanceAndCredit(

        @WebParam(partName = "querySumBalanceAndCreditRequest", name = "querySumBalanceAndCredit", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices")
        QuerySumBalanceAndCredit querySumBalanceAndCreditRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/queryTotalBalance")
    @WebResult(name = "queryTotalBalanceResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", partName = "queryTotalBalanceResponse")
    public QueryTotalBalanceResponse queryTotalBalance(

        @WebParam(partName = "queryTotalBalanceRequest", name = "queryTotalBalance", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices")
        QueryTotalBalance queryTotalBalanceRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/arservices/queryLoanLog")
    @WebResult(name = "queryLoanLogResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", partName = "queryLoanLogResponse")
    public QueryLoanLogResponse queryLoanLog(

        @WebParam(partName = "queryLoanLogRequest", name = "queryLoanLog", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices")
        QueryLoanLog queryLoanLogRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/arservices/queryRechargeLog")
    @WebResult(name = "queryRechargeLogResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", partName = "queryRechargeLogResponse")
    public QueryRechargeLogResponse queryRechargeLog(

        @WebParam(partName = "queryRechargeLogRequest", name = "queryRechargeLog", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices")
        QueryRechargeLog queryRechargeLogRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/queryTransaction")
    @WebResult(name = "queryTransactionResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", partName = "queryTransactionResponse")
    public QueryTransactionResponse queryTransaction(

        @WebParam(partName = "queryTransactionRequest", name = "queryTransaction", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices")
        QueryTransaction queryTransactionRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/queryRefundLog")
    @WebResult(name = "queryRefundLogResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", partName = "queryRefundLogResponse")
    public QueryRefundLogResponse queryRefundLog(

        @WebParam(partName = "queryRefundLogRequest", name = "queryRefundLog", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices")
        QueryRefundLog queryRefundLogRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/queryInvoiceDetail")
    @WebResult(name = "queryInvoiceDetailResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", partName = "queryInvoiceDetailResponse")
    public QueryInvoiceDetailResponse queryInvoiceDetail(

        @WebParam(partName = "queryInvoiceDetailRequest", name = "queryInvoiceDetail", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices")
        QueryInvoiceDetail queryInvoiceDetailRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/queryAdjustLog")
    @WebResult(name = "queryAdjustLogResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", partName = "queryAdjustLogResponse")
    public QueryAdjustLogResponse queryAdjustLog(

        @WebParam(partName = "queryAdjustLogRequest", name = "queryAdjustLog", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices")
        QueryAdjustLog queryAdjustLogRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/queryBalance")
    @WebResult(name = "queryBalanceResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", partName = "queryBalanceResponse")
    public QueryBalanceResponse queryBalance(

        @WebParam(partName = "queryBalanceRequest", name = "queryBalance", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices")
        QueryBalance queryBalanceRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/queryCustomerArrears")
    @WebResult(name = "queryCustomerArrearsResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", partName = "queryCustomerArrearsResponse")
    public QueryCustomerArrearsResponse queryCustomerArrears(

        @WebParam(partName = "queryCustomerArrearsRequest", name = "queryCustomerArrears", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices")
        QueryCustomerArrears queryCustomerArrearsRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/transferBalance")
    @WebResult(name = "transferBalanceResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", partName = "transferBalanceResponse")
    public TransferBalanceResponse transferBalance(

        @WebParam(partName = "transferBalanceRequest", name = "transferBalance", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices")
        TransferBalance transferBalanceRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/adv2Deposit")
    @WebResult(name = "adv2DepositResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", partName = "adv2DepositResponse")
    public Adv2DepositResponse adv2Deposit(

        @WebParam(partName = "adv2DepositRequest", name = "adv2Deposit", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices")
        Adv2Deposit adv2DepositRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/arservices/rechargeRollBack")
    @WebResult(name = "rechargeRollBackResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", partName = "rechargeRollBackResponse")
    public RechargeRollBackResponse rechargeRollBack(

        @WebParam(partName = "rechargeRollBackRequest", name = "rechargeRollBack", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices")
        RechargeRollBack rechargeRollBackRequest
    ) throws GeneralException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices/queryDepositBalance")
    @WebResult(name = "queryDepositBalanceResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices", partName = "queryDepositBalanceResponse")
    public QueryDepositBalanceResponse queryDepositBalance(

        @WebParam(partName = "queryDepositBalanceRequest", name = "queryDepositBalance", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices")
        QueryDepositBalance queryDepositBalanceRequest
    ) throws GeneralException;
}
