
package mx.com.telcel.sipab.client.cbs;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-10-24T12:33:03.522-06:00
 * Generated source version: 4.0.3
 */

@WebFault(name = "generalException", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/bes/esb/arservices")
public class GeneralException extends Exception {

    private mx.com.telcel.sipab.client.cbs.ArServicesException faultInfo;

    public GeneralException() {
        super();
    }

    public GeneralException(String message) {
        super(message);
    }

    public GeneralException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public GeneralException(String message, mx.com.telcel.sipab.client.cbs.ArServicesException generalException) {
        super(message);
        this.faultInfo = generalException;
    }

    public GeneralException(String message, mx.com.telcel.sipab.client.cbs.ArServicesException generalException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = generalException;
    }

    public mx.com.telcel.sipab.client.cbs.ArServicesException getFaultInfo() {
        return this.faultInfo;
    }
}
