
package mx.com.telcel.sipab.client.sicatel;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-10-24T12:33:32.710-06:00
 * Generated source version: 4.0.3
 */

@WebFault(name = "consultarPagosExtException", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/gsce/dsrvcte/operacionespagosservice")
public class ConsultarPagosExtException extends Exception {

    private mx.com.telcel.sipab.client.sicatel.OperacionesPagosServiceException faultInfo;

    public ConsultarPagosExtException() {
        super();
    }

    public ConsultarPagosExtException(String message) {
        super(message);
    }

    public ConsultarPagosExtException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ConsultarPagosExtException(String message, mx.com.telcel.sipab.client.sicatel.OperacionesPagosServiceException consultarPagosExtException) {
        super(message);
        this.faultInfo = consultarPagosExtException;
    }

    public ConsultarPagosExtException(String message, mx.com.telcel.sipab.client.sicatel.OperacionesPagosServiceException consultarPagosExtException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = consultarPagosExtException;
    }

    public mx.com.telcel.sipab.client.sicatel.OperacionesPagosServiceException getFaultInfo() {
        return this.faultInfo;
    }
}
