package mx.com.telcel.sipab.client.sicatel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-10-24T12:33:32.748-06:00
 * Generated source version: 4.0.3
 *
 */
@WebServiceClient(name = "OperacionesPagosServiceHttpService",
                  wsdlLocation = "http://sicatelws.telcelinstitucional.com/SicatelWSPagosSistExt/OperacionesPagosServiceHttpBindingImpl?wsdl",
                  targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/gsce/dsrvcte/operacionespagosservice")
public class OperacionesPagosServiceHttpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.amx.com.mx/mexico/telcel/di/sds/gsce/dsrvcte/operacionespagosservice", "OperacionesPagosServiceHttpService");
    public final static QName OperacionesPagosServiceHttpPort = new QName("http://www.amx.com.mx/mexico/telcel/di/sds/gsce/dsrvcte/operacionespagosservice", "OperacionesPagosServiceHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://sicatelws.telcelinstitucional.com/SicatelWSPagosSistExt/OperacionesPagosServiceHttpBindingImpl?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OperacionesPagosServiceHttpService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://sicatelws.telcelinstitucional.com/SicatelWSPagosSistExt/OperacionesPagosServiceHttpBindingImpl?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OperacionesPagosServiceHttpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OperacionesPagosServiceHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OperacionesPagosServiceHttpService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public OperacionesPagosServiceHttpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OperacionesPagosServiceHttpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OperacionesPagosServiceHttpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns OperacionesPagosService
     */
    @WebEndpoint(name = "OperacionesPagosServiceHttpPort")
    public OperacionesPagosService getOperacionesPagosServiceHttpPort() {
        return super.getPort(OperacionesPagosServiceHttpPort, OperacionesPagosService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OperacionesPagosService
     */
    @WebEndpoint(name = "OperacionesPagosServiceHttpPort")
    public OperacionesPagosService getOperacionesPagosServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(OperacionesPagosServiceHttpPort, OperacionesPagosService.class, features);
    }

}
