package mx.com.telcel.sipab.client.sicatel;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-10-24T12:33:32.727-06:00
 * Generated source version: 4.0.3
 *
 */
@WebService(targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/gsce/dsrvcte/operacionespagosservice", name = "OperacionesPagosService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OperacionesPagosService {

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/gsce/dsrvcte/operacionespagosservice/registrarPagosPorAplicarExt")
    @WebResult(name = "registrarPagosPorAplicarExtResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/gsce/dsrvcte/operacionespagosservice", partName = "registrarPagosPorAplicarExtResponse")
    public RegistrarPagosPorAplicarExtResponse registrarPagosPorAplicarExt(

        @WebParam(partName = "registrarPagosPorAplicarExtRequest", name = "registrarPagosPorAplicarExt", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/gsce/dsrvcte/operacionespagosservice")
        RegistrarPagosPorAplicarExt registrarPagosPorAplicarExtRequest
    ) throws RegistrarPagosPorAplicarExtException;

    @WebMethod(action = "http://www.amx.com.mx/mexico/telcel/di/sds/gsce/dsrvcte/operacionespagosservice/consultarPagosExt")
    @WebResult(name = "consultarPagosExtResponse", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/gsce/dsrvcte/operacionespagosservice", partName = "consultarPagosExtResponse")
    public ConsultarPagosExtResponse consultarPagosExt(

        @WebParam(partName = "consultarPagosExtRequest", name = "consultarPagosExt", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/gsce/dsrvcte/operacionespagosservice")
        ConsultarPagosExt consultarPagosExtRequest
    ) throws ConsultarPagosExtException;
}
