
package mx.com.telcel.sipab.client.sicatel;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-10-24T12:33:32.691-06:00
 * Generated source version: 4.0.3
 */

@WebFault(name = "registrarPagosPorAplicarExtException", targetNamespace = "http://www.amx.com.mx/mexico/telcel/di/sds/gsce/dsrvcte/operacionespagosservice")
public class RegistrarPagosPorAplicarExtException extends Exception {

    private mx.com.telcel.sipab.client.sicatel.OperacionesPagosServiceException faultInfo;

    public RegistrarPagosPorAplicarExtException() {
        super();
    }

    public RegistrarPagosPorAplicarExtException(String message) {
        super(message);
    }

    public RegistrarPagosPorAplicarExtException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public RegistrarPagosPorAplicarExtException(String message, mx.com.telcel.sipab.client.sicatel.OperacionesPagosServiceException registrarPagosPorAplicarExtException) {
        super(message);
        this.faultInfo = registrarPagosPorAplicarExtException;
    }

    public RegistrarPagosPorAplicarExtException(String message, mx.com.telcel.sipab.client.sicatel.OperacionesPagosServiceException registrarPagosPorAplicarExtException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = registrarPagosPorAplicarExtException;
    }

    public mx.com.telcel.sipab.client.sicatel.OperacionesPagosServiceException getFaultInfo() {
        return this.faultInfo;
    }
}
